/* Generated by scripts/build-client.mjs from src/client/index.js — do not edit by hand. */
window.__ModuleLoader__.load({
  id: "dsh-mywork-oracle",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    var __prelude = {};
    var __hostRequire = require;
    require = function (id) { var k = String(id).replace(/^\.\//, "").replace(/^src\//, ""); if (Object.prototype.hasOwnProperty.call(__prelude, k)) return __prelude[k]; var base = k.split("/").pop(); if (Object.prototype.hasOwnProperty.call(__prelude, base)) return __prelude[base]; return __hostRequire(id); };
    __prelude["client-icons.cjs"] = (function () { var module = { exports: {} }; var exports = module.exports;
/**
 * Shared monochrome line icons for the MyWork Kit browser bundles (inlined into
 * each lib/client.js by scripts/build-client.mjs as a prelude).
 *
 * Paths follow the lucide icon set (ISC): 24×24 viewBox, stroke = currentColor,
 * so they match dsh's own toolbar icons and follow the active theme.
 *
 *   const { icon } = require('./client-icons.cjs')
 *   icon('link')                 → React element, 16px
 *   icon('bell', { size: 18 })
 */
'use strict'

const React = require('react')

const PATHS = {
  'alarm-clock': ['M12 21a8 8 0 1 0 0-16 8 8 0 0 0 0 16z', 'M12 9v4l2 2', 'M5 3 2 6', 'm22 6-3-3', 'M6.38 18.7 4 21', 'M17.64 18.67 2.35 2.33'],
  bell: ['M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9', 'M10.3 21a1.94 1.94 0 0 0 3.4 0'],
  link: ['M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71', 'M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71'],
  globe: ['M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z', 'M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20', 'M2 12h20'],
  'external-link': ['M15 3h6v6', 'M10 14 21 3', 'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6'],
  x: ['M18 6 6 18', 'm6 6 12 12'],
  plus: ['M5 12h14', 'M12 5v14'],
  'arrow-left': ['m12 19-7-7 7-7', 'M19 12H5'],
  'arrow-right': ['M5 12h14', 'm12 5 7 7-7 7'],
  'refresh-cw': ['M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8', 'M21 3v5h-5', 'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16', 'M8 16H3v5'],
  'chevron-up': ['m18 15-6-6-6 6'],
  'chevron-down': ['m6 9 6 6 6-6'],
  pencil: ['M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z', 'm15 5 4 4'],
  pause: ['M6 4h4v16H6z', 'M14 4h4v16h-4z'],
  play: ['M6 3l14 9-14 9V3z'],
  'trending-up': ['M22 7l-8.5 8.5-5-5L2 17', 'M16 7h6v6'],
  activity: ['M22 12h-4l-3 9L9 3l-3 9H2'],
  crosshair: ['M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z', 'M22 12h-4', 'M6 12H2', 'M12 6V2', 'M12 22v-4'],
  check: ['M20 6 9 17l-5-5'],
  trash: ['M3 6h18', 'M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6', 'M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2', 'M10 11v6', 'M14 11v6'],
  palette: ['M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z', 'M13.5 6.5h.01', 'M17.5 10.5h.01', 'M6.5 12.5h.01', 'M8.5 7.5h.01'],
  'panel-left': ['M3 5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z', 'M9 3v18'],
  type: ['M4 7V4h16v3', 'M9 20h6', 'M12 4v16'],
  calendar: ['M8 2v4', 'M16 2v4', 'M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z', 'M3 10h18'],
  'bar-chart': ['M12 20V10', 'M18 20V4', 'M6 20v-4'],
  store: ['M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z', 'M3 6h18', 'M16 10a4 4 0 0 1-8 0'],
  package: ['M16.5 9.4 7.55 4.24', 'M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z', 'M3.27 6.96 12 12.01l8.73-5.05', 'M12 22.08V12'],
  'monitor-play': ['M10 7.75a.75.75 0 0 1 1.14-.64l3.25 2a.75.75 0 0 1 0 1.28l-3.25 2a.75.75 0 0 1-1.14-.64z', 'M12 17v4', 'M8 21h8', 'M4 3h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z'],
  bookmark: ['m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z'],
  search: ['M11 19a8 8 0 1 0 0-16 8 8 0 0 0 0 16z', 'm21 21-4.3-4.3'],
  history: ['M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8', 'M3 3v5h5', 'M12 7v5l4 2'],
  'bookmark-plus': ['m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z', 'M12 7v6', 'M9 10h6'],
  'list-checks': ['m3 17 2 2 4-4', 'm3 7 2 2 4-4', 'M13 6h8', 'M13 12h8', 'M13 18h8'],
  settings: ['M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z', 'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z'],
  sheet: ['M3 5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z', 'M3 9h18', 'M3 15h18', 'M9 9v12', 'M15 9v12'],
  plug: ['M12 22v-5', 'M9 8V2', 'M15 8V2', 'M18 8v5a6 6 0 0 1-12 0V8z'],
  message: ['M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z'],
  send: ['M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z', 'm21.854 2.147-10.94 10.939'],
  'square-arrow-out': ['M21 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6', 'm21 3-9 9', 'M15 3h6v6'],
}

/**
 * Build an inline SVG icon element.
 * @param {string} name - a key of PATHS
 * @param {{ size?: number, strokeWidth?: number, className?: string, style?: object }} [opts]
 */
function icon(name, opts) {
  const o = opts || {}
  const size = o.size || 16
  const paths = PATHS[name] || PATHS.x
  return React.createElement('svg', {
    width: size, height: size, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor',
    strokeWidth: o.strokeWidth || 1.75, strokeLinecap: 'round', strokeLinejoin: 'round',
    'aria-hidden': 'true', focusable: 'false', className: o.className, style: { display: 'block', flex: 'none', ...(o.style || {}) },
  }, paths.map((d, i) => React.createElement('path', { key: i, d })))
}

module.exports = { icon, PATHS }

    return module.exports; })();
/**
 * dsh-mywork-oracle — browser half: the "市场先知" tab in 设置 → MyWork (slot `mywork.settings.tab`).
 * Shows the Python / yfinance state, runs a live self-check and installs yfinance on request.
 */
'use strict'
const React = require('react')
const { icon } = require('./client-icons.cjs')
const PLUGIN = 'dsh-mywork-oracle'
const NS = 'mywork.oracle'
const API = '/mywork-oracle/api'
const TAB_SLOT = 'mywork.settings.tab'

const zh = {
  nav: '市场先知', title: 'Digital Oracle · 市场数据先知',
  intro: '用市场交易数据（预测市场、期权、国债曲线、机构持仓、内部人交易、加密衍生品、A 股资金流）回答「这件事概率多大」「现在值不值得买」。模型在对话里自动使用 oracle_* 工具；新建对话页有「市场先知」起点。只做分析，不下单。',
  env: '运行环境', python: 'Python', yfinance: 'yfinance（美股价格历史 / 期权链）', providers: '数据源', version: '内置版本', ok: '可用', missing: '未安装', bad: '不可用',
  selfcheck: '自检（联网拉三组数据）', checking: '检查中…', install: '安装 yfinance', installing: '安装中…（1–3 分钟）',
  result: '结果', errors: '失败的数据源', refresh: '刷新',
  examples: '可以问的问题', ex1: 'WW3 的概率是多少？', ex2: '现在适合买黄金吗？', ex3: '比特币到底了吗？', ex4: '600519 主力资金最近在买还是卖？', ex5: 'NVDA 期权溢价是不是太高了？',
  credit: '基于 komako-workshop/digital-oracle（MIT）',
}
const en = {
  nav: 'Market oracle', title: 'Digital Oracle · market-data oracle',
  intro: 'Answers "how likely is X" and "is Y worth buying now" from trading data only: prediction markets, options, yield curves, CFTC positioning, insider filings, crypto derivatives, A-share fund flow. The model uses the oracle_* tools by itself; the new-conversation page has a "Market oracle" starting point. Analysis only, no orders.',
  env: 'Environment', python: 'Python', yfinance: 'yfinance (US price history / options chains)', providers: 'Data sources', version: 'Bundled version', ok: 'ready', missing: 'not installed', bad: 'unavailable',
  selfcheck: 'Self-check (fetches three live signals)', checking: 'Checking…', install: 'Install yfinance', installing: 'Installing… (1–3 min)',
  result: 'Result', errors: 'Failed sources', refresh: 'Refresh',
  examples: 'Questions to try', ex1: 'What is the probability of WW3?', ex2: 'Is it a good time to buy gold?', ex3: 'Has Bitcoin bottomed?', ex4: 'Is institutional money buying or selling 600519?', ex5: 'Is NVDA options premium too high?',
  credit: 'Powered by komako-workshop/digital-oracle (MIT)',
}

const CSS = `
.mwo{font-size:13px;color:var(--dsw-alias-label-primary);max-width:720px}
.mwo h3{margin:0 0 6px;font-size:15px;display:flex;align-items:center;gap:8px}
.mwo .intro{color:var(--dsw-alias-label-secondary);line-height:1.65;margin-bottom:14px}
.mwo .card{border:0.5px solid var(--dsw-alias-border-l2);border-radius:12px;padding:12px 14px;margin-bottom:14px;background:var(--dsw-alias-bg-layer-1)}
.mwo .card h4{margin:0 0 8px;font-size:13px;color:var(--dsw-alias-label-secondary);font-weight:600}
.mwo table{border-collapse:collapse;width:100%}
.mwo td{padding:4px 0;vertical-align:top}
.mwo td:first-child{color:var(--dsw-alias-label-secondary);width:46%}
.mwo .ok{color:var(--dsw-alias-state-success-primary)}
.mwo .bad{color:var(--dsw-alias-state-error-primary)}
.mwo .row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:10px}
.mwo .btn{border:0;border-radius:8px;background:var(--dsw-alias-button-primary-fill,var(--dsw-alias-brand-primary));color:var(--dsw-alias-label-primary-inverted,#fff);padding:6px 14px;cursor:pointer;font:inherit;font-weight:600;display:inline-flex;gap:6px;align-items:center}
.mwo .btn:disabled{opacity:.5;cursor:default}
.mwo .mini{border:0.5px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-secondary);border-radius:8px;padding:5px 10px;cursor:pointer;font:inherit;font-size:12px}
.mwo pre{margin:8px 0 0;white-space:pre-wrap;word-break:break-word;font-size:12px;background:var(--dsw-alias-bg-layer-2);border-radius:8px;padding:8px 10px;max-height:220px;overflow:auto}
.mwo ul{margin:0;padding-left:18px;line-height:1.7;color:var(--dsw-alias-label-secondary)}
.mwo .credit{font-size:12px;color:var(--dsw-alias-label-tertiary)}
`
async function api(path, body) {
  const res = await fetch(API + path, body === undefined ? { method: 'GET' } : { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) })
  const data = await res.json().catch(() => ({}))
  if (!res.ok) throw new Error(data && data.error ? data.error : 'HTTP ' + res.status)
  return data
}

exports.name = PLUGIN
exports.inject = ['slots', 'locale']
exports.apply = function apply(ctx) {
  ctx.effect(() => { const el = document.createElement('style'); el.setAttribute('data-plugin', PLUGIN); el.textContent = CSS; document.head.appendChild(el); return () => el.remove() }, `${PLUGIN}: stylesheet`)
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), `${PLUGIN}: dictionaries`)
  const t = ctx.locale.bind(NS)
  const h = React.createElement

  function Tab() {
    const [st, setSt] = React.useState(null)
    const [busy, setBusy] = React.useState('')
    const [out, setOut] = React.useState(null)
    const load = React.useCallback(() => api('/status').then(setSt).catch((e) => setSt({ ok: false, pythonError: String(e.message || e) })), [])
    React.useEffect(() => { load() }, [load])
    const run = async (kind) => {
      setBusy(kind); setOut(null)
      try { const r = await api(kind === 'check' ? '/selfcheck' : '/install-yfinance', {}); setOut(r); load() } catch (e) { setOut({ error: String(e.message || e) }) } finally { setBusy('') }
    }
    const state = (ok, label) => h('span', { className: ok ? 'ok' : 'bad' }, label)
    return h('div', { className: 'mwo' },
      h('h3', null, icon('trending-up', { size: 16 }), t('title')),
      h('div', { className: 'intro' }, t('intro')),
      h('div', { className: 'card' }, h('h4', null, t('env')),
        st === null ? h('div', null, '…') : h('table', null, h('tbody', null,
          h('tr', null, h('td', null, t('python')), h('td', null, st.pythonVersion ? state(true, `${st.pythonVersion} · ${st.pythonCmd}`) : state(false, st.pythonError || t('bad')))),
          h('tr', null, h('td', null, t('yfinance')), h('td', null, st.yfinance ? state(true, t('ok')) : state(false, t('missing')))),
          h('tr', null, h('td', null, t('providers')), h('td', null, Array.isArray(st.providers) ? String(st.providers.length) : state(false, st.runnerError || t('bad')))),
          h('tr', null, h('td', null, t('version')), h('td', null, st.version || '—')))),
        h('div', { className: 'row' },
          h('button', { className: 'btn', disabled: !!busy || !(st && st.ok), onClick: () => run('check') }, icon('activity', { size: 13 }), busy === 'check' ? t('checking') : t('selfcheck')),
          st && st.ok && !st.yfinance ? h('button', { className: 'mini', disabled: !!busy, onClick: () => run('install') }, busy === 'install' ? t('installing') : t('install')) : null,
          h('button', { className: 'mini', disabled: !!busy, onClick: load }, t('refresh'))),
        out ? h('pre', null, out.error ? out.error : [
          `${t('result')}: ${out.ok ? 'OK' : 'FAIL'}${out.ms ? ` · ${out.ms} ms` : ''}`,
          out.summary ? JSON.stringify(out.summary) : '',
          out.errors && Object.keys(out.errors).length ? `${t('errors')}: ${JSON.stringify(out.errors)}` : '',
          out.command ? `$ ${out.command}\n${out.output || ''}` : '',
        ].filter(Boolean).join('\n')) : null),
      h('div', { className: 'card' }, h('h4', null, t('examples')), h('ul', null, ['ex1', 'ex2', 'ex3', 'ex4', 'ex5'].map((k) => h('li', { key: k }, t(k))))),
      h('div', { className: 'credit' }, t('credit')),
    )
  }
  ctx.slots.inject(TAB_SLOT, () => ctx.slots.register({ name: TAB_SLOT, id: 'oracle', order: 60, label: () => t('nav') }, function MyworkOracleTab() { return h(Tab) }))
}

    return module.exports;
  }
});
