/**
 * dsh-mywork-tasks — what code does for teammates doing AI work (design/v2/AI-WORKERS.md), as tools any teammate can
 * call. A teammate is generated by MyWork (from a playbook or from scratch); these are the facts code supplies so the
 * model need not be trusted with them:
 *
 *   mywork_arxiv_today   the day's whole arXiv list for the categories in AGENTS.md (苏剑林: no pre-filter, no paper missed)
 *   mywork_cite_check    every reference looked up on arXiv / Crossref (ARIS, ICLR 2026: a failed request is never 查无)
 *   mywork_loop          连续跑: code calls the next round until a time (autoresearch's NEVER STOP, Anthropic's long runs)
 *   mywork_results       the numbers in results.tsv (best so far, kept / discarded / crashed, last night's run)
 *   mywork_wiki_check    the wiki's orphans, broken links and pages missing from the index (Karpathy's lint)
 *   mywork_hand_to       hand work (and files) to another teammate; it shows there as 「<name> 转交」
 *
 * and, without a tool: a routine with `loopUntil` (过夜实验) starts 连续跑 with its run as round one; a report with
 * 「> 未经你审」 under its title (Simon Willison) gets 审过了 where it is read (POST /mates/review).
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { basename, extname, isAbsolute, join, relative, resolve } from 'node:path'
import { categoriesOf, DAILY_DIR, fetchDaily, readDay, readTriage, saveDay, titleLines, triagePath } from './arxiv.js'
import { checkEntries, DRAFT_DIR, readDraft, saveCheck } from './cite.js'
import { markReviewed } from './projects.js'
import { ledgerLine, readLedger, summarize } from './results.js'
import { lintFindings, scanWiki } from './wiki.js'

const pad = (n) => String(n).padStart(2, '0')
const dayOf = (d = new Date()) => d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate())
const hhmm = (iso) => { const d = new Date(iso); return pad(d.getHours()) + ':' + pad(d.getMinutes()) }
/** Rounds of one 连续跑 at most, and how many rounds in a row without a new result end it. */
export const LOOP_MAX = 200
export const LOOP_IDLE = 3
const INLINE_TITLES = 20000
const HAND_FILES_MAX = 20

/** `dropDirOf(mate)` is where files handed to a teammate go; `pump()` hands queued runs over; `fetch` is injectable. */
export function createCapabilities({ store, mates, routines, emit, pump, log, bad, dropDirOf, fetch: f, now = () => new Date() }) {
  const doFetch = (...a) => (f || globalThis.fetch)(...a)
  const readText = (p) => { try { return readFileSync(p, 'utf8') } catch { return '' } }
  /** A done run posted by code into a teammate's thread: one line of text. */
  function postLine(mateId, text, patch = {}) {
    const at = now().toISOString()
    const run = store.create({ mateId, trigger: 'system', input: '', status: 'done' })
    store.update(run.id, { startedAt: at, finishedAt: at, summary: text, ...patch, activity: [{ kind: 'text', text, at }] })
    emit('done', store.get(run.id))
    return store.get(run.id)
  }

  // ── arXiv ──
  /** The day's whole list into 每日/: the JSON, the titles of new and cross-listed papers, the updated ones apart. */
  async function arxivToday(m, given) {
    const cats = (Array.isArray(given) ? given : String(given || '').split(/[\s,，、+]+/)).map((x) => String(x).trim()).filter(Boolean)
    const want = cats.length ? cats : categoriesOf(readText(join(m.dir, 'AGENTS.md')))
    if (!want.length) return { error: 'AGENTS.md 里还没写分类：加一行「- 分类：cs.CL, cs.LG」，或者调用时传 categories。' }
    let day
    try { day = await fetchDaily(want, { fetch: doFetch }) } catch (e) { return { error: '没取到 arXiv 的表：' + ((e && e.message) || e) + '。可以用浏览器打开 https://arxiv.org/list/<分类>/new 自己过。', cats: want } }
    if (!day.items.length) return { empty: true, cats: day.cats, note: '今天 arXiv 没有新表（周末或美国假日）。' }
    const seen = !!(readDay(m.dir, day.date) && readTriage(m.dir, day.date))
    saveDay(m.dir, day)
    const fresh = day.items.filter((p) => p.type === 'new' || p.type === 'cross')
    const updated = day.items.filter((p) => p.type !== 'new' && p.type !== 'cross')
    const lines = titleLines(fresh)
    writeFileSync(join(m.dir, DAILY_DIR, day.date + '.标题.txt'), lines + '\n')
    writeFileSync(join(m.dir, DAILY_DIR, day.date + '.更新.txt'), titleLines(updated) + '\n')
    const count = (t) => day.items.filter((p) => p.type === t).length
    return {
      date: day.date, cats: day.cats, total: day.items.length, new: count('new'), cross: count('cross'), updated: updated.length, alreadyDone: seen,
      files: { list: `${DAILY_DIR}/${day.date}.json`, titles: `${DAILY_DIR}/${day.date}.标题.txt`, updated: `${DAILY_DIR}/${day.date}.更新.txt`, triage: triagePath(day.date) },
      titles: lines.length <= INLINE_TITLES ? lines : '',
    }
  }

  // ── 连续跑 ──
  /** 'HH:MM' → the next time the clock shows it; minutes → that long from now. */
  function untilOf({ until, minutes }) {
    const t = now()
    if (Number(minutes) > 0) return new Date(t.getTime() + Math.min(Number(minutes), 72 * 60) * 60000).toISOString()
    const m = String(until || '').match(/^(\d{1,2})[:：](\d{2})$/)
    if (!m || Number(m[1]) > 23 || Number(m[2]) > 59) throw bad('until 写成 HH:MM，比如 07:00。')
    const d = new Date(t)
    d.setHours(Number(m[1]), Number(m[2]), 0, 0)
    if (d.getTime() <= t.getTime()) d.setDate(d.getDate() + 1)
    return d.toISOString()
  }
  const loopView = (m) => (m && m.loop && m.loop.active ? { until: m.loop.until, rounds: m.loop.rounds, startedAt: m.loop.startedAt } : null)
  function startLoop(m, until) {
    const rows = readLedger(m.dir).rows.length
    const prev = m.loop && m.loop.active ? m.loop : null
    const loop = prev ? { ...prev, until } : { id: 'lp-' + now().getTime().toString(36), active: true, until, startedAt: now().toISOString(), rounds: 0, idle: 0, errors: 0, rowsAtStart: rows, lastRows: rows }
    mates.update(m.id, { loop })
    emit('mate', null, { mateId: m.id })
    return loop
  }
  /** The loop ends with a line by code: how long, how many rounds, and the numbers when the teammate keeps results.tsv. */
  function finishLoop(m, why) {
    const L = m && m.loop
    if (!L || !L.active) return false
    const at = now().toISOString()
    mates.update(m.id, { loop: { ...L, active: false, endedAt: at, why } })
    const { rows, dir, metric } = readLedger(m.dir)
    const numbers = rows.length ? ledgerLine(summarize(rows, dir, L.rowsAtStart), metric) : ''
    postLine(m.id, `连续跑结束（${why}）：${hhmm(L.startedAt)}–${hhmm(at)}，${L.rounds} 轮。${numbers}`, { loopEnd: L.id })
    emit('mate', null, { mateId: m.id })
    return true
  }
  /**
   * After each turn (and on the scheduler tick): the next round, unless it is time, it has gone idle (3 rounds in a row
   * without a new results.tsv row — for a teammate without one, without a changed file), it failed twice, or someone
   * else has the turn.
   */
  function continueLoop(mateId) {
    const m = mates.get(mateId)
    const L = m && m.loop
    if (!L || !L.active) return
    const runs = store.forMate(mateId)
    if (runs.some((r) => r.status === 'queued' || r.status === 'running' || r.status === 'waiting')) return
    const last = [...runs].reverse().find((r) => r.status === 'done' && !r.loopEnd)
    if (last && last.stopped) return finishLoop(m, '你停下了')
    const rows = readLedger(m.dir).rows.length
    const changed = (r) => !!r && (r.activity || []).some((a) => a && a.kind === 'did' && (a.act === 'file' || a.act === 'files'))
    const progressed = rows || L.lastRows ? rows > L.lastRows : changed(last)
    const idle = progressed ? 0 : (L.idle || 0) + 1
    const errors = last && last.error && last.loop === L.id ? (L.errors || 0) + 1 : 0
    if (now().getTime() >= Date.parse(L.until)) return finishLoop(m, '到点了')
    if (errors >= 2) return finishLoop(m, '连续出错：' + String(last.error).slice(0, 60))
    if (idle >= LOOP_IDLE) return finishLoop(m, `连续 ${LOOP_IDLE} 轮没有新结果`)
    if (L.rounds >= LOOP_MAX) return finishLoop(m, `跑满 ${LOOP_MAX} 轮`)
    const n = (L.rounds || 0) + 1
    mates.update(mateId, { loop: { ...L, rounds: n, idle, errors, lastRows: rows } })
    const { rows: all, dir, metric } = readLedger(m.dir)
    const run = store.create({ mateId, trigger: 'system', input: '' })
    store.update(run.id, {
      loop: L.id, loopRound: n,
      prompt: [
        `（连续跑 · 第 ${n} 轮 · 到 ${hhmm(L.until)} 为止。这句话是 MyWork 替用户发的，用户看不到。）`,
        all.length
          ? '接着做下一个实验：先看 PROGRESS.md 的「下一步」和 results.tsv 的最后几行，挑一个改动，照 program.md 做完一次实验并记账（results.tsv 加一行，PROGRESS.md 更新），然后结束这一轮，回一句话：试了什么、结果、留还是丢。'
          : '接着做下一步：先看你的进度记在哪（AGENTS.md 里写着），做完一步并把进度记下来，然后结束这一轮，回一句话：做了什么、结果。',
        '不要问要不要继续，不要说「明天再说」，不要停下来写总结：下一轮程序会再叫你，到点它自己停。没有思路时去读代码里引用的论文、把差一点成功的改动组合起来、试更大胆的做法。',
        idle ? `（上一轮没有新结果；连续 ${LOOP_IDLE} 轮没有新结果程序就会停下。卡住了就在这一轮把原因记下来。）` : '',
        all.length ? `到现在：${ledgerLine(summarize(all, dir, L.rowsAtStart), metric)}` : '',
      ].filter(Boolean).join('\n'),
    })
    emit('queued', store.get(run.id))
    pump()
  }
  /** A routine with `loopUntil` (过夜实验): its run is round one, and the loop starts with it. */
  function startLoopRoutine(r, m) {
    const until = untilOf({ until: r.loopUntil })
    const loop = startLoop(m, until)
    const { rows, dir, metric } = readLedger(m.dir)
    const run = store.create({ mateId: m.id, trigger: 'routine', routineId: r.id, routineTitle: r.title, input: r.input })
    store.update(run.id, {
      loop: loop.id, loopRound: 0,
      prompt: [
        `（例行《${r.title}》。这句话是 MyWork 替用户发的，用户看不到。）这一次连续干到 ${hhmm(until)}：程序会一轮接一轮地叫你，每轮做一步。`,
        '这是第一轮：先确认东西能跑（机器、代码、上次的改动已经提交或回退），做第一步并记下来，然后结束这一轮，回一句话。',
        r.input,
        rows.length ? `到现在：${ledgerLine(summarize(rows, dir), metric)}` : '',
      ].filter(Boolean).join('\n'),
    })
    routines.ran(r.id, { taskId: run.id })
    emit('queued', store.get(run.id))
    pump()
    return run.id
  }

  // ── results.tsv ──
  function results(m) {
    const { rows, dir, metric } = readLedger(m.dir)
    if (!rows.length) return { empty: true, note: 'results.tsv 还没有记录（或者没有这个文件）。' }
    const all = summarize(rows, dir)
    const L = m.loop
    const night = L && L.endedAt && now().getTime() - Date.parse(L.endedAt) < 16 * 3600000 ? { from: hhmm(L.startedAt), to: hhmm(L.endedAt), rounds: L.rounds, why: L.why, line: ledgerLine(summarize(rows, dir, L.rowsAtStart), metric) } : null
    return { metric, direction: dir === 'higher' ? '越高越好' : '越低越好', line: ledgerLine(all, metric), best: all.best, baseline: all.baseline, lastLoop: night, latest: all.last }
  }

  // ── hand over ──
  /** The teammate a name or an id names (never the caller). */
  function mateNamed(who, from) {
    const w = String(who || '').trim()
    if (!w) return null
    const list = mates.items.filter((x) => x.id !== from.id)
    return list.find((x) => x.id === w) || list.find((x) => x.name === w) || list.find((x) => !!x.name && (x.name.includes(w) || w.includes(x.name))) || null
  }
  /** Files from the caller's folder into the other teammate's drop folder, and a line there from the caller. */
  function handTo(from, { to, text, files }) {
    const target = mateNamed(to, from)
    if (!target) throw bad(`没有叫「${to}」的同事。现有的：${mates.items.filter((x) => x.id !== from.id).map((x) => x.name).filter(Boolean).join('、') || '无'}`)
    const said = String(text || '').trim()
    if (!said) throw bad('text 写清要它做什么。')
    const drop = dropDirOf(target)
    const copied = []
    for (const p of (Array.isArray(files) ? files : []).slice(0, HAND_FILES_MAX)) {
      const full = resolve(from.dir, String(p || ''))
      const inside = relative(resolve(from.dir), full)
      if (!inside || inside.startsWith('..') || isAbsolute(inside)) throw bad(`只能交你自己文件夹里的文件：${p}`)
      if (!existsSync(full) || !statSync(full).isFile()) throw bad(`没有这个文件：${p}`)
      mkdirSync(join(target.dir, drop), { recursive: true })
      const ext = extname(full)
      const stem = basename(full, ext)
      let name = basename(full)
      for (let i = 2; existsSync(join(target.dir, drop, name)); i += 1) name = `${stem} (${i})${ext}`
      copyFileSync(full, join(target.dir, drop, name))
      copied.push(drop + '/' + name)
    }
    const input = copied.length ? `${said}\n（在 ${drop}/：${copied.map((x) => x.split('/').pop()).join('、')}）` : said
    const run = store.create({ mateId: target.id, trigger: 'user', input, source: 'mate' })
    store.update(run.id, { fromMate: from.id })
    emit('queued', store.get(run.id))
    pump()
    log(`hand-over ${from.id} → ${target.id}: ${said.slice(0, 40)}`)
    return { to: { id: target.id, name: target.name || '' }, files: copied, runId: run.id }
  }

  // ── 核引用 ──
  const checking = new Map()
  async function citeCheck(m, dir) {
    const sub = String(dir || DRAFT_DIR).replace(/^\.?\/+|\/+$/g, '') || DRAFT_DIR
    if (sub.split(/[\\/]/).includes('..') || isAbsolute(sub)) throw bad('dir 只能是你文件夹里的子文件夹。')
    if (checking.has(m.id)) return checking.get(m.id)
    const job = (async () => {
      const draft = readDraft(m.dir, sub)
      if (!draft.entries.length) return { empty: true, dir: sub, files: draft.files }
      const res = await checkEntries(draft.entries, draft.cites, { fetch: doFetch })
      const paths = saveCheck(m.dir, dayOf(now()), res)
      return { ...paths, counts: res.counts, files: draft.files }
    })()
    checking.set(m.id, job)
    try { return await job } finally { checking.delete(m.id) }
  }

  /** POST /mates/review: 「> 未经你审」 under a report's title becomes 「> 审过：date」 (you read it and say so). */
  function review(m, path) {
    const rel = String(path || '')
    const full = resolve(m.dir, rel)
    const inside = relative(resolve(m.dir), full)
    if (!inside || inside.startsWith('..') || isAbsolute(inside) || !/\.md$/i.test(rel)) throw bad('只能标它文件夹里的 .md。')
    try { markReviewed(m.dir, inside, dayOf(now())) } catch (e) { throw bad(e.message) }
    emit('mate', null, { mateId: m.id })
    return { path: inside.split('\\').join('/'), reviewed: dayOf(now()) }
  }

  const tools = [
    {
      name: 'mywork_arxiv_today',
      description: '取今天 arXiv 的全表（程序取，一篇不漏）：按你 AGENTS.md 里「分类：」那一行（或传 categories）取当天的新论文、交叉列出的和更新的，存进 每日/日期.json，新和交叉的标题清单存进 每日/日期.标题.txt。返回篇数、文件和（不太长时）标题清单。今天没有新表会说明。',
      parameters: { categories: { type: 'string', description: '可选，arXiv 分类代号，逗号隔开，例如 cs.CL, cs.LG；不给就用 AGENTS.md 里的' } },
      async execute(args, m) { return arxivToday(m, args.categories) },
      render: (_a, v) => [{ type: 'text', text: v.error ? v.error : v.empty ? v.note + '只回一句，最后一行写「变化：无」。' : `程序取到了 ${v.date} 的 arXiv 全表（${v.cats.join(', ')}）：${v.total} 篇 —— 新 ${v.new} · 交叉 ${v.cross} · 更新 ${v.updated}。${v.alreadyDone ? '这一天你已经过过了（' + v.files.triage + ' 已经有了），除非用户要你重过，只回一句，最后一行写「变化：无」。' : ''}新和交叉的标题${v.titles ? '如下' : '在 ' + v.files.titles}，逐行看完，一篇不跳；摘要在 ${v.files.list}；更新的在 ${v.files.updated}。分流写进 ${v.files.triage}，论文一律写 arXiv 号。${v.titles ? '\n' + v.titles : ''}` }],
    },
    {
      name: 'mywork_cite_check',
      description: '核引用：程序把一个文件夹（默认 稿子/）里每条参考文献到 arXiv 和 Crossref 查一遍——存不存在、标题 / 第一作者 / 年份对不对——并找出每条引用所在的句子，写成 核引用/日期.md 和 .json（json 里有查到的摘要）。投稿前、改过参考文献后用；查一次要几十秒。',
      parameters: { dir: { type: 'string', description: '可选，稿子所在的子文件夹，默认 稿子' } },
      async execute(args, m) { return citeCheck(m, args.dir) },
      render: (_a, v) => [{ type: 'text', text: v.empty ? `${v.dir}/ 里没有 .bib（看到的文件：${(v.files || []).join('、') || '无'}）。请用户把 .bib 和稿子放进 ${v.dir}/。` : `程序查完了：${v.counts.total} 条 —— 核实 ${v.counts.ok} · 元数据不符 ${v.counts.mismatch} · 查无此文 ${v.counts.missing} · 待查 ${v.counts.pending} · 网页或软件 ${v.counts.web}${v.counts.undefined ? ' · 不在 .bib 里 ' + v.counts.undefined : ''}。报告在 ${v.md}，明细（含查到的摘要和每条引用的原句）在 ${v.json}。接下来：对每条引用判断查到的文献是否支持原句（支持 / 弱 / 不支持）；元数据不符的直接改 .bib；查无此文、不支持、要换或删的列给用户拍板；判断写进报告末尾「## 是否支持原句」一节。待查是请求失败，不算查无。` }],
    },
    {
      name: 'mywork_loop',
      description: '连续干到某个时间：程序会一轮接一轮地叫你接着做，到点才停，你不用自己判断要不要继续。用户说「跑到明早 7 点」「接着跑一晚上」「再跑两个小时」时调用；用户说停就传 stop: true。调用后照常做完这一轮再结束。连续 3 轮没有新结果（results.tsv 没加行；没有这个文件就是没改文件）、连续 2 轮出错，程序也会停。',
      parameters: {
        until: { type: 'string', description: '到几点停，HH:MM（今天或明天的这个时间）' },
        minutes: { type: 'number', description: '或者：再跑多少分钟' },
        stop: { type: 'boolean', description: 'true 就停下连续跑' },
      },
      execute(args, m) {
        if (args.stop) return { stopped: finishLoop(m, '你停下了') }
        const loop = startLoop(m, untilOf(args))
        return { until: loop.until, untilLocal: hhmm(loop.until) }
      },
      render: (_a, v) => [{ type: 'text', text: v.stopped !== undefined ? '连续跑已停下。' : `好的，程序会一轮接一轮地叫你，到 ${v.untilLocal} 为止。这一轮照常做完一步、记下来，然后结束这一轮。` }],
    },
    {
      name: 'mywork_results',
      description: '程序从你的 results.tsv（commit / 指标 / 显存 / keep·discard·crash / 说明）和 program.md（「指标：」「越低/越高越好」）算好的成绩：一共几次、留几次、最好成绩和基线、最近几次、上一次连续跑的成绩。写成绩、早报时以它为准。',
      parameters: {},
      execute(_args, m) { return results(m) },
    },
    {
      name: 'mywork_wiki_check',
      description: '程序查你的 wiki/：多少页、多少份原始资料、孤立页（除了索引没有别的页链到它）、断链、没进 index.md 的页、最近的日志。体检时先调它，再自己查矛盾、过时的说法和该有却没有的页。',
      parameters: {},
      execute(_args, m) { const scan = scanWiki(m.dir); return { pages: scan.pages.length, findings: lintFindings(scan), log: scan.log.slice(0, 5) } },
    },
    {
      name: 'mywork_hand_to',
      description: '把一件事交给另一位同事（比如把论文交给知识库、把结论交给写论文的同事）：to 是它的名字，text 是你替用户交代的话，files 是你文件夹里要一起交过去的文件（会拷进它收文件的文件夹）。它那边会出现「<你的名字> 转交」的一句，由它接着做。',
      parameters: {
        to: { type: 'string', required: true, description: '接手的同事的名字（左边列表里的名字）' },
        text: { type: 'string', required: true, description: '交代的话，例如「收进知识库：Trained Agentic Context Management」' },
        files: { type: 'array', items: { type: 'string' }, description: '可选，你文件夹里的文件路径（相对路径），最多 20 个' },
      },
      execute(args, m) { return handTo(m, args) },
      render: (_a, v) => [{ type: 'text', text: `已交给「${v.to.name}」${v.files.length ? '，文件：' + v.files.join('、') : ''}。用一句话告诉用户交给了谁、它会接着做什么。` }],
    },
  ]

  return { tools, continueLoop, finishLoop, loopView, startLoopRoutine, review, handTo, arxivToday, citeCheck, results }
}
