/* Generated by scripts/build-client.mjs from src/client/index.js — do not edit by hand. */
window.__ModuleLoader__.load({
  id: "dsh-mywork-schedule",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    var __prelude = {};
    var __hostRequire = require;
    require = function (id) { var k = String(id).replace(/^\.\//, "").replace(/^src\//, ""); if (Object.prototype.hasOwnProperty.call(__prelude, k)) return __prelude[k]; var base = k.split("/").pop(); if (Object.prototype.hasOwnProperty.call(__prelude, base)) return __prelude[base]; return __hostRequire(id); };
    __prelude["logic.cjs"] = (function () { var module = { exports: {} }; var exports = module.exports;
/**
 * dsh-mywork-schedule — pure scheduling logic shared by the host (Node ESM via
 * createRequire) and the browser bundle (inlined by scripts/build-client.mjs).
 *
 * No I/O, no globals except Date. All "local" calculations use the caller's
 * timezone (the browser where the alarm fires, or the host machine for the
 * /remind command), which is the natural meaning of "09:00 every day".
 *
 * Reminder shape (JSON):
 *   {
 *     id: string, title: string, note?: string,
 *     kind: 'once' | 'daily' | 'weekly' | 'interval',
 *     at?: string            // once:     RFC 3339 instant
 *     time?: 'HH:MM'         // daily / weekly: local wall-clock time
 *     weekdays?: number[]    // weekly:   1 = Monday … 7 = Sunday
 *     everyMinutes?: number  // interval: >= 1
 *     enabled: boolean, createdAt: string, lastFiredAt?: string, sessionId?: string
 *   }
 */
'use strict'

const KINDS = ['once', 'daily', 'weekly', 'interval']
const GRACE_MS = 24 * 60 * 60 * 1000 // fire "missed" alarms up to a day late

function pad2(n) { return (n < 10 ? '0' : '') + n }

/** Parse 'HH:MM' → { h, m } or null. */
function parseTime(text) {
  const m = /^(\d{1,2}):(\d{2})$/.exec(String(text || '').trim())
  if (!m) return null
  const h = Number(m[1]); const mi = Number(m[2])
  if (h < 0 || h > 23 || mi < 0 || mi > 59) return null
  return { h, m: mi }
}

/** ISO weekday of a Date in local time: 1 = Monday … 7 = Sunday. */
function isoWeekday(d) { const w = d.getDay(); return w === 0 ? 7 : w }

/** Parse a relative duration like 10m, 2h, 1h30m, 45s, 2d → milliseconds or null. */
function parseDuration(text) {
  const s = String(text || '').trim().toLowerCase()
  if (!s) return null
  const re = /(\d+(?:\.\d+)?)\s*(d|h|m|s|天|小时|分钟|分|秒)/g
  let total = 0; let matched = ''
  let m
  while ((m = re.exec(s)) !== null) {
    const n = Number(m[1]); const u = m[2]
    matched += m[0]
    if (u === 'd' || u === '天') total += n * 86400000
    else if (u === 'h' || u === '小时') total += n * 3600000
    else if (u === 'm' || u === '分钟' || u === '分') total += n * 60000
    else total += n * 1000
  }
  if (matched.replace(/\s/g, '') !== s.replace(/\s/g, '')) return null
  return total > 0 ? total : null
}

/** Validate a reminder-like object; returns { ok: true, value } or { ok: false, error }. */
function normalize(input) {
  if (input === null || typeof input !== 'object') return { ok: false, error: 'reminder must be an object' }
  const title = typeof input.title === 'string' ? input.title.trim() : ''
  if (!title) return { ok: false, error: 'title is required' }
  const kind = input.kind || (input.at ? 'once' : input.everyMinutes ? 'interval' : input.weekdays ? 'weekly' : input.time ? 'daily' : 'once')
  if (!KINDS.includes(kind)) return { ok: false, error: `kind must be one of ${KINDS.join(', ')}` }
  const out = { title, kind, enabled: input.enabled !== false }
  if (typeof input.note === 'string' && input.note.trim()) out.note = input.note.trim()
  if (typeof input.sessionId === 'string' && input.sessionId) out.sessionId = input.sessionId
  // optional IM delivery (dsh-mywork-im): true = most recent chat, or a target string
  if (input.im === true) out.im = true; else if (typeof input.im === 'string' && input.im.trim()) out.im = input.im.trim()
  if (kind === 'once') {
    const at = input.at ? new Date(input.at) : null
    if (!at || Number.isNaN(at.getTime())) return { ok: false, error: 'once reminders need a valid `at` instant (RFC 3339)' }
    out.at = at.toISOString()
  } else if (kind === 'daily' || kind === 'weekly') {
    const t = parseTime(input.time)
    if (!t) return { ok: false, error: '`time` must be HH:MM' }
    out.time = pad2(t.h) + ':' + pad2(t.m)
    if (kind === 'weekly') {
      const days = Array.isArray(input.weekdays) ? input.weekdays.map(Number).filter((d) => Number.isInteger(d) && d >= 1 && d <= 7) : []
      if (days.length === 0) return { ok: false, error: 'weekly reminders need `weekdays` (1 = Monday … 7 = Sunday)' }
      out.weekdays = Array.from(new Set(days)).sort((a, b) => a - b)
    }
  } else {
    const n = Number(input.everyMinutes)
    if (!Number.isFinite(n) || n < 1) return { ok: false, error: '`everyMinutes` must be >= 1' }
    out.everyMinutes = Math.round(n)
  }
  return { ok: true, value: out }
}

/**
 * Next occurrence strictly after `after` (a Date), in the caller's local time.
 * Returns a Date or null (a `once` reminder that already passed `after`).
 */
function nextOccurrence(r, after) {
  const from = after instanceof Date ? after : new Date(after)
  if (r.kind === 'once') {
    const at = new Date(r.at)
    return at.getTime() > from.getTime() ? at : null
  }
  if (r.kind === 'interval') {
    const anchor = new Date(r.lastFiredAt || r.createdAt || from)
    const step = r.everyMinutes * 60000
    let t = anchor.getTime() + step
    if (t <= from.getTime()) {
      const k = Math.floor((from.getTime() - anchor.getTime()) / step) + 1
      t = anchor.getTime() + k * step
    }
    return new Date(t)
  }
  const tm = parseTime(r.time)
  if (!tm) return null
  const cand = new Date(from.getFullYear(), from.getMonth(), from.getDate(), tm.h, tm.m, 0, 0)
  for (let i = 0; i < 8; i++) {
    if (cand.getTime() > from.getTime()) {
      if (r.kind === 'daily') return new Date(cand)
      if (r.weekdays.includes(isoWeekday(cand))) return new Date(cand)
    }
    cand.setDate(cand.getDate() + 1)
    cand.setHours(tm.h, tm.m, 0, 0)
  }
  return null
}

/**
 * The occurrence that is due right now, if any: the latest occurrence after
 * `lastFiredAt` (or creation) that is <= now and not older than the grace
 * window. Returns a Date or null.
 */
function dueOccurrence(r, now) {
  if (!r.enabled) return null
  const nowD = now instanceof Date ? now : new Date(now)
  const after = new Date(r.lastFiredAt || r.createdAt || 0)
  let next = nextOccurrence(r, after)
  if (!next) return null
  if (next.getTime() > nowD.getTime()) return null
  // Skip forward to the most recent due occurrence (no backlog).
  let due = next
  for (let i = 0; i < 1000; i++) {
    const n = nextOccurrence(r, due)
    if (!n || n.getTime() > nowD.getTime()) break
    due = n
  }
  if (nowD.getTime() - due.getTime() > GRACE_MS) {
    // Too old to be a meaningful alarm; treat as skipped but still report so
    // the caller can advance lastFiredAt silently.
    return { at: due, stale: true }
  }
  return { at: due, stale: false }
}

/** Human summary of the rule (for tool output / lists). */
function describe(r, lang) {
  const zh = lang === 'zh'
  const names = zh ? ['一', '二', '三', '四', '五', '六', '日'] : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  if (r.kind === 'once') return zh ? '一次' : 'once'
  if (r.kind === 'daily') return (zh ? '每天 ' : 'daily ') + r.time
  if (r.kind === 'weekly') return (zh ? '每周' : 'weekly ') + r.weekdays.map((d) => names[d - 1]).join(zh ? '、' : ',') + ' ' + r.time
  const m = r.everyMinutes
  const txt = m % 60 === 0 ? (m / 60) + 'h' : m + 'm'
  return (zh ? '每 ' : 'every ') + txt
}

/**
 * Parse the free text of `/remind …` into a reminder input (local time).
 *   /remind 10m 喝水               → once, now + 10m
 *   /remind 18:30 下班             → once, today 18:30 (tomorrow if passed)
 *   /remind daily 09:00 站会       → daily
 *   /remind weekly 1,3,5 10:00 周会 → weekly (1 = Mon … 7 = Sun)
 *   /remind every 30m 喝水         → interval
 * Returns { ok: true, value } or { ok: false, error }.
 */
function parseCommand(raw, now) {
  const nowD = now instanceof Date ? now : new Date(now || Date.now())
  const text = String(raw || '').trim()
  if (!text) return { ok: false, error: 'usage' }
  const parts = text.split(/\s+/)
  const head = parts[0].toLowerCase()
  if (head === 'daily' || head === '每天') {
    const t = parseTime(parts[1])
    if (!t) return { ok: false, error: 'daily needs HH:MM' }
    const title = parts.slice(2).join(' ')
    return normalize({ title, kind: 'daily', time: parts[1] })
  }
  if (head === 'weekly' || head === '每周') {
    const days = String(parts[1] || '').split(/[，,]/).map(Number)
    const t = parseTime(parts[2])
    if (!t) return { ok: false, error: 'weekly needs days and HH:MM' }
    return normalize({ title: parts.slice(3).join(' '), kind: 'weekly', weekdays: days, time: parts[2] })
  }
  if (head === 'every' || head === '每') {
    const ms = parseDuration(parts[1])
    if (!ms) return { ok: false, error: 'every needs a duration like 30m' }
    return normalize({ title: parts.slice(2).join(' '), kind: 'interval', everyMinutes: Math.max(1, Math.round(ms / 60000)) })
  }
  const t = parseTime(parts[0])
  if (t) {
    const at = new Date(nowD.getFullYear(), nowD.getMonth(), nowD.getDate(), t.h, t.m, 0, 0)
    if (at.getTime() <= nowD.getTime()) at.setDate(at.getDate() + 1)
    return normalize({ title: parts.slice(1).join(' '), kind: 'once', at: at.toISOString() })
  }
  const ms = parseDuration(parts[0])
  if (ms) return normalize({ title: parts.slice(1).join(' '), kind: 'once', at: new Date(nowD.getTime() + ms).toISOString() })
  return { ok: false, error: 'unrecognized time' }
}

module.exports = { KINDS, GRACE_MS, parseTime, parseDuration, normalize, nextOccurrence, dueOccurrence, describe, parseCommand, isoWeekday }

    return module.exports; })();
    __prelude["client-icons.cjs"] = (function () { var module = { exports: {} }; var exports = module.exports;
/**
 * Shared monochrome line icons for the MyWork Kit browser bundles (inlined into
 * each lib/client.js by scripts/build-client.mjs as a prelude).
 *
 * Paths follow the lucide icon set (ISC): 24×24 viewBox, stroke = currentColor,
 * so they match dsh's own toolbar icons and follow the active theme.
 *
 *   const { icon } = require('./client-icons.cjs')
 *   icon('link')                 → React element, 16px
 *   icon('bell', { size: 18 })
 */
'use strict'

const React = require('react')

const PATHS = {
  'alarm-clock': ['M12 21a8 8 0 1 0 0-16 8 8 0 0 0 0 16z', 'M12 9v4l2 2', 'M5 3 2 6', 'm22 6-3-3', 'M6.38 18.7 4 21', 'M17.64 18.67 2.35 2.33'],
  bell: ['M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9', 'M10.3 21a1.94 1.94 0 0 0 3.4 0'],
  link: ['M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71', 'M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71'],
  globe: ['M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z', 'M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20', 'M2 12h20'],
  'external-link': ['M15 3h6v6', 'M10 14 21 3', 'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6'],
  x: ['M18 6 6 18', 'm6 6 12 12'],
  plus: ['M5 12h14', 'M12 5v14'],
  'arrow-left': ['m12 19-7-7 7-7', 'M19 12H5'],
  'arrow-right': ['M5 12h14', 'm12 5 7 7-7 7'],
  'refresh-cw': ['M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8', 'M21 3v5h-5', 'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16', 'M8 16H3v5'],
  'chevron-up': ['m18 15-6-6-6 6'],
  'chevron-down': ['m6 9 6 6 6-6'],
  pencil: ['M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z', 'm15 5 4 4'],
  pause: ['M6 4h4v16H6z', 'M14 4h4v16h-4z'],
  play: ['M6 3l14 9-14 9V3z'],
  crosshair: ['M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z', 'M22 12h-4', 'M6 12H2', 'M12 6V2', 'M12 22v-4'],
  check: ['M20 6 9 17l-5-5'],
  trash: ['M3 6h18', 'M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6', 'M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2', 'M10 11v6', 'M14 11v6'],
  palette: ['M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z', 'M13.5 6.5h.01', 'M17.5 10.5h.01', 'M6.5 12.5h.01', 'M8.5 7.5h.01'],
  'panel-left': ['M3 5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z', 'M9 3v18'],
  type: ['M4 7V4h16v3', 'M9 20h6', 'M12 4v16'],
  calendar: ['M8 2v4', 'M16 2v4', 'M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z', 'M3 10h18'],
  'bar-chart': ['M12 20V10', 'M18 20V4', 'M6 20v-4'],
  store: ['M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z', 'M3 6h18', 'M16 10a4 4 0 0 1-8 0'],
  package: ['M16.5 9.4 7.55 4.24', 'M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z', 'M3.27 6.96 12 12.01l8.73-5.05', 'M12 22.08V12'],
  'monitor-play': ['M10 7.75a.75.75 0 0 1 1.14-.64l3.25 2a.75.75 0 0 1 0 1.28l-3.25 2a.75.75 0 0 1-1.14-.64z', 'M12 17v4', 'M8 21h8', 'M4 3h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z'],
  bookmark: ['m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z'],
  search: ['M11 19a8 8 0 1 0 0-16 8 8 0 0 0 0 16z', 'm21 21-4.3-4.3'],
  history: ['M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8', 'M3 3v5h5', 'M12 7v5l4 2'],
  'bookmark-plus': ['m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z', 'M12 7v6', 'M9 10h6'],
  'list-checks': ['m3 17 2 2 4-4', 'm3 7 2 2 4-4', 'M13 6h8', 'M13 12h8', 'M13 18h8'],
  settings: ['M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z', 'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z'],
  sheet: ['M3 5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z', 'M3 9h18', 'M3 15h18', 'M9 9v12', 'M15 9v12'],
  plug: ['M12 22v-5', 'M9 8V2', 'M15 8V2', 'M18 8v5a6 6 0 0 1-12 0V8z'],
  message: ['M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z'],
  send: ['M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z', 'm21.854 2.147-10.94 10.939'],
  'square-arrow-out': ['M21 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6', 'm21 3-9 9', 'M15 3h6v6'],
}

/**
 * Build an inline SVG icon element.
 * @param {string} name - a key of PATHS
 * @param {{ size?: number, strokeWidth?: number, className?: string, style?: object }} [opts]
 */
function icon(name, opts) {
  const o = opts || {}
  const size = o.size || 16
  const paths = PATHS[name] || PATHS.x
  return React.createElement('svg', {
    width: size, height: size, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor',
    strokeWidth: o.strokeWidth || 1.75, strokeLinecap: 'round', strokeLinejoin: 'round',
    'aria-hidden': 'true', focusable: 'false', className: o.className, style: { display: 'block', flex: 'none', ...(o.style || {}) },
  }, paths.map((d, i) => React.createElement('path', { key: i, d })))
}

module.exports = { icon, PATHS }

    return module.exports; })();
/**
 * dsh-mywork-schedule — browser half (CommonJS; wrapped by scripts/build-client.mjs,
 * with src/logic.cjs inlined as a prelude so `require('./logic.cjs')` works).
 *
 * Surfaces:
 *   • "日程" button at the right of the composer (conversation.input.right) with a
 *     badge for enabled reminders; click toggles the panel.
 *   • Floating panel (shell.overlay) with two tabs:
 *       提醒   — alarm-style reminders (this package)
 *       定时任务 — scheduled sessions from @michengai/dsh-automation; the tab links
 *                to its settings page (Automation has no readable HTTP API).
 *   • Alarm toasts (shell.overlay).
 *   • "日程" tab inside Settings → MyWork: notification permission, sound, list.
 *   • "运行结束发到 IM" field inside Automation's own task dialog + a chip on each task
 *     card (DOM injection, see installNotifyInjector; rules live in dsh-mywork-im).
 *
 * Alarms fire HERE: the client polls the host list, computes due occurrences
 * with the browser's clock/timezone, shows a toast, a browser Notification
 * (if permitted) and a short beep (WebAudio, no asset), then tells the host
 * `/fired` so other tabs and the model tools agree on lastFiredAt.
 */
'use strict'

const React = require('react')
const logic = require('./logic.cjs')
const { icon } = require('./client-icons.cjs')

const PLUGIN = 'dsh-mywork-schedule'
const NS = 'mywork.schedule'
const API = '/mywork-schedule/api'
const TAB_SLOT = 'mywork.settings.tab'
/** Settings-section labels of @michengai/dsh-automation (zh / en). */
const AUTOMATION_LABELS = ['定时任务', 'Scheduled tasks']
/** Standalone 定时任务 main panel registered by dsh-mywork-codex-ui. */
const SCHEDULE_PANEL_ID = 'mywork-schedule'
const POLL_MS = 30000
const TICK_MS = 5000
const SOUND_KEY = 'dsh-mywork-schedule:sound'
/** lucide "send" as inline SVG for the card chip (Automation's chips are plain spans). */
const ICON_SEND = '<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"/><path d="m21.854 2.147-10.94 10.939"/></svg>'

const zh = {
  nav: '日程',
  title: '日程',
  reminders: '提醒',
  tasks: '定时任务',
  tasksHint: '定时任务在独立会话里按计划执行编码任务（一次 / 每小时 / 每天 / 每周 / 每月），由 Automation 插件提供；在侧栏「定时」标签查看，在设置页管理。',
  tasksOpen: '打开定时任务页面',
  tasksMissing: '尚未安装 @michengai/dsh-automation：到 设置 → MyWork → 成员 一键补装。',
  notifyTitle: '运行结束发到 IM', notifyFieldHint: '跑完后把最后一条回复发到这个微信 / 飞书聊天，随任务一起保存。也可以在对话里说"这个任务完成后发到微信"。', notifyOff: '不发送', notifyAlways: '每次结束', notifyFailed: '仅失败', notifyNoChats: '还没有可发的聊天：先在 IM 里给机器人发一句。', notifyUnknownChat: '聊天已不可用',
  add: '添加',
  cancel: '取消',
  empty: '还没有提醒。用下面的表单，或在对话里说「10 分钟后提醒我…」，或输入 /remind 10m 喝水。',
  placeholder: '提醒内容',
  note: '备注（可选）',
  once: '一次', daily: '每天', weekly: '每周', interval: '间隔',
  minutes: '分钟',
  next: '下次',
  overdue: '已过期',
  fired: '提醒',
  missed: '（错过，已延迟提示）',
  enable: '启用', pause: '暂停', remove: '删除', confirm: '确认删除',
  notif: '浏览器通知',
  notifOn: '已允许', notifOff: '未允许 · 点此申请', notifDenied: '已被浏览器拒绝', notifNA: '当前环境不支持',
  sound: '提示音',
  on: '开', off: '关',
  toggle: '日程面板',
  help: '到点时会在页面内弹出、发浏览器通知并播放提示音（需保持 DSH 页面打开）。模型也可以用 reminder_* 工具替你设置。数据文件：',
  weekdays: ['一', '二', '三', '四', '五', '六', '日'],
  dismiss: '知道了',
  toIm: '到点也发到 IM（微信等）',
  imSent: '已发到 IM',
}
const en = {
  nav: 'Schedule',
  title: 'Schedule',
  reminders: 'Reminders',
  tasks: 'Scheduled tasks',
  tasksHint: 'Scheduled tasks run coding jobs in their own sessions on a plan (once / hourly / daily / weekly / monthly), provided by the Automation plugin; see them in the sidebar "Schedule" tab and manage them in Settings.',
  tasksOpen: 'Open the scheduled tasks page',
  tasksMissing: '@michengai/dsh-automation is not installed: Settings → MyWork → Members installs it in one click.',
  notifyTitle: 'Send the result to IM when a run ends', notifyFieldHint: 'The last reply of each run goes to this WeChat / Feishu chat; saved with the task. You can also ask in chat ("send this task\'s result to WeChat").', notifyOff: 'do not send', notifyAlways: 'every run', notifyFailed: 'failed only', notifyNoChats: 'No reachable chat yet: message the bot from your IM app first.', notifyUnknownChat: 'chat no longer available',
  add: 'Add',
  cancel: 'Cancel',
  empty: 'No reminders yet. Use the form below, ask the model ("remind me in 10 minutes…"), or type /remind 10m water.',
  placeholder: 'What to remind',
  note: 'Note (optional)',
  once: 'Once', daily: 'Daily', weekly: 'Weekly', interval: 'Every',
  minutes: 'min',
  next: 'next',
  overdue: 'overdue',
  fired: 'Reminder',
  missed: ' (missed, shown late)',
  enable: 'Enable', pause: 'Pause', remove: 'Delete', confirm: 'Confirm',
  notif: 'Browser notifications',
  notifOn: 'granted', notifOff: 'not granted · click to request', notifDenied: 'blocked by the browser', notifNA: 'unavailable here',
  sound: 'Sound',
  on: 'on', off: 'off',
  toggle: 'Schedule panel',
  help: 'Due reminders pop up in this page, send a browser notification and play a beep (keep the DSH page open). The model can also manage them with the reminder_* tools. Data file:',
  weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  dismiss: 'OK',
  toIm: 'Also send to IM (WeChat, …) when due',
  imSent: 'sent to IM',
}

const CSS = `
.mwr-btn{display:inline-flex;align-items:center;justify-content:center;background:transparent;border:0;border-radius:8px;width:28px;height:28px;padding:0;cursor:pointer;color:var(--dsw-alias-label-secondary);position:relative}
.mwr-btn:hover,.mwr-btn.active{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}
.mwr-badge{position:absolute;top:-4px;right:-2px;min-width:14px;height:14px;padding:0 4px;border-radius:7px;background:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary-inverted,#fff);font-size:9px;line-height:14px;text-align:center;font-weight:600}
.mwr-panel{position:fixed;right:18px;bottom:92px;width:360px;max-width:calc(100vw - 32px);max-height:min(72vh,640px);display:flex;flex-direction:column;background:var(--dsw-alias-bg-overlay,var(--dsw-alias-bg-layer-1));color:var(--dsw-alias-label-primary);border:0;border-radius:14px;box-shadow:var(--dsw-elevation-prominent,0 10px 40px rgba(0,0,0,.28));z-index:1200;pointer-events:auto;font-size:13px;overflow:hidden}
.mwr-head{display:flex;align-items:center;gap:8px;padding:10px 12px;border-bottom:0.5px solid var(--dsw-alias-border-l2);font-weight:600}
.mwr-head .sp{flex:1}
.mwr-tabs{display:flex;gap:2px;padding:6px 8px 0}
.mwr-tab{border:0;background:transparent;color:var(--dsw-alias-label-secondary);padding:5px 10px;border-radius:8px;cursor:pointer;font:inherit;font-size:12.5px}
.mwr-tab:hover{background:var(--dsw-alias-interactive-bg-hover)}
.mwr-tab.on{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font-weight:600}
.mwr-tasks{padding:14px 12px;display:flex;flex-direction:column;gap:10px;color:var(--dsw-alias-label-secondary);line-height:1.6}
.mwr-x{border:0;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;padding:0;width:24px;height:24px;display:inline-flex;align-items:center;justify-content:center;border-radius:6px}
.mwr-x:hover{background:var(--dsw-alias-interactive-bg-hover)}
.mwr-list{flex:1;overflow:auto;padding:6px 8px}
.mwr-empty{padding:16px 10px;color:var(--dsw-alias-label-secondary);line-height:1.6}
.mwr-row{display:flex;gap:8px;align-items:flex-start;padding:8px;border-radius:10px}
.mwr-row:hover{background:var(--dsw-alias-interactive-bg-hover)}
.mwr-row.off{opacity:.55}
.mwr-main{flex:1;min-width:0}
.mwr-title{font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.mwr-meta{display:flex;gap:6px;flex-wrap:wrap;align-items:center;font-size:12px;color:var(--dsw-alias-label-secondary);margin-top:2px}
.mwr-pill{background:var(--dsw-alias-bg-layer-2);border-radius:5px;padding:0 6px;line-height:17px}
.mwr-pill.due{color:var(--dsw-alias-state-warn-primary)}
.mwr-note{font-size:12px;color:var(--dsw-alias-label-secondary);margin-top:2px;white-space:pre-wrap}
.mwr-acts{display:flex;gap:2px;flex:none}
.mwr-mini{border:0;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font-size:12px;padding:0 6px;height:24px;display:inline-flex;align-items:center;gap:4px;border-radius:6px;font-family:inherit}
.mwr-mini:hover{background:var(--dsw-alias-interactive-bg-active);color:var(--dsw-alias-label-primary)}
.mwr-mini.danger{color:var(--dsw-alias-state-error-primary)}
.mwr-form{padding:10px 12px;border-top:0.5px solid var(--dsw-alias-border-l2);display:flex;flex-direction:column;gap:6px}
.mwr-in{width:100%;box-sizing:border-box;background:var(--dsw-alias-bg-layer-2);border:0.5px solid var(--dsw-alias-border-l2);border-radius:8px;padding:6px 9px;font:inherit;color:inherit}
.mwr-in:focus{outline:none;border-color:var(--dsw-alias-brand-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-brand-primary) 35%,transparent)}
.mwr-line{display:flex;gap:6px;align-items:center;flex-wrap:wrap}
.mwr-line .mwr-in{width:auto;flex:1;min-width:90px}
.mwr-seg{display:inline-flex;border:0.5px solid var(--dsw-alias-border-l2);border-radius:8px;overflow:hidden}
.mwr-seg button{border:0;background:transparent;color:var(--dsw-alias-label-secondary);padding:4px 9px;cursor:pointer;font:inherit;font-size:12px}
.mwr-seg button.on{background:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary-inverted,#fff)}
.mwr-wd{display:flex;gap:3px}
.mwn-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
.mwn-select{flex:1;min-width:200px;height:35px;padding:0 10px;border-radius:12px;border:0.5px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);color:inherit;font:inherit;font-size:13.3px}
.mwn-select:focus{outline:none;border-color:var(--dsw-alias-brand-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-brand-primary) 35%,transparent)}
.mwn-hint{font-size:12px;color:var(--dsw-alias-label-secondary);line-height:1.5}
.mwn-chip svg{width:14px;height:14px}
.mwn-chip{white-space:nowrap;min-height:24px;color:var(--dsw-alias-label-primary)}
.dsh-st-card-foot{flex-wrap:wrap;row-gap:6px}
.mwr-wd button{width:26px;height:26px;border-radius:50%;corner-shape:round;border:0.5px solid var(--dsw-alias-border-l2);background:transparent;color:inherit;cursor:pointer;font-size:11px;padding:0}
.mwr-wd button.on{background:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary-inverted,#fff);border-color:transparent}
.mwr-primary{border:0;border-radius:8px;background:var(--dsw-alias-button-primary-fill,var(--dsw-alias-brand-primary));color:var(--dsw-alias-label-primary-inverted,#fff);padding:6px 14px;cursor:pointer;font:inherit;font-weight:600}
.mwr-primary:disabled{opacity:.5;cursor:default}
.mwr-err{color:var(--dsw-alias-state-error-primary);font-size:12px}
.mwr-toasts{position:fixed;top:16px;right:18px;display:flex;flex-direction:column;gap:8px;z-index:1300;pointer-events:none}
.mwr-toast{pointer-events:auto;width:340px;max-width:calc(100vw - 32px);background:var(--dsw-alias-bg-overlay,var(--dsw-alias-bg-layer-1));color:var(--dsw-alias-label-primary);border-radius:12px;box-shadow:var(--dsw-elevation-prominent,0 10px 40px rgba(0,0,0,.28));padding:12px 14px;display:flex;gap:10px;align-items:flex-start;animation:mwr-in .25s ease}
.mwr-toast{animation:mwr-toast-in 260ms cubic-bezier(.2,.8,.2,1) both}
.mwr-toast.out{animation:mwr-toast-out 180ms ease-in both;pointer-events:none}
@keyframes mwr-toast-in{from{opacity:0;transform:translateY(-10px) scale(.98)}to{opacity:1;transform:none}}
@keyframes mwr-toast-out{from{opacity:1;transform:none}to{opacity:0;transform:translateY(-8px)}}
.mwn-chip.mwn-flash{animation:mwn-flash 700ms ease-out}
@keyframes mwn-flash{0%{box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-brand-primary) 55%,transparent);background:color-mix(in srgb,var(--dsw-alias-brand-primary) 18%,transparent)}100%{box-shadow:0 0 0 0 transparent}}
@media (prefers-reduced-motion:reduce){.mwr-toast,.mwr-toast.out,.mwn-chip.mwn-flash{animation:none}}
.mwr-toast .ic{color:var(--dsw-alias-brand-primary);padding-top:2px}
.mwr-toast .tt{font-weight:600}
.mwr-toast .ts{font-size:12px;color:var(--dsw-alias-label-secondary);margin-top:2px}
.mwr-toast .mwr-primary{padding:4px 10px;font-size:12px;align-self:center}
@keyframes mwr-in{from{transform:translateY(-8px);opacity:0}to{transform:none;opacity:1}}
.mwr-set{display:flex;flex-direction:column;gap:10px;font-size:13px}
.mwr-set .row{display:flex;align-items:center;gap:10px}
.mwr-set .row .lab{width:140px;color:var(--dsw-alias-label-secondary)}
.mwr-set code{font-family:ui-monospace,Menlo,monospace;font-size:12px;color:var(--dsw-alias-label-secondary)}
`

function injectStyles() {
  const el = document.createElement('style')
  el.setAttribute('data-plugin', PLUGIN)
  el.textContent = CSS
  document.head.appendChild(el)
  return () => { el.remove() }
}

async function api(path, body) {
  const res = await fetch(API + path, body === undefined ? { method: 'GET' } : {
    method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body),
  })
  const data = await res.json().catch(() => ({}))
  if (!res.ok) throw new Error(data && data.error ? data.error : 'HTTP ' + res.status)
  return data
}

function beep() {
  try {
    const Ctx = window.AudioContext || window.webkitAudioContext
    if (!Ctx) return
    const ac = new Ctx()
    const now = ac.currentTime
    ;[0, 0.18, 0.36].forEach((off, i) => {
      const o = ac.createOscillator(); const g = ac.createGain()
      o.type = 'sine'; o.frequency.value = i === 2 ? 1046 : 880
      g.gain.setValueAtTime(0.0001, now + off)
      g.gain.exponentialRampToValueAtTime(0.25, now + off + 0.02)
      g.gain.exponentialRampToValueAtTime(0.0001, now + off + 0.16)
      o.connect(g); g.connect(ac.destination)
      o.start(now + off); o.stop(now + off + 0.18)
    })
    setTimeout(() => { try { ac.close() } catch { /* ignore */ } }, 1200)
  } catch { /* audio blocked */ }
}

function soundEnabled() { try { return window.localStorage.getItem(SOUND_KEY) !== 'off' } catch { return true } }
function setSound(on) { try { window.localStorage.setItem(SOUND_KEY, on ? 'on' : 'off') } catch { /* ignore */ } }

function fmt(d) {
  if (!d) return '—'
  const dt = d instanceof Date ? d : new Date(d)
  const now = new Date()
  const sameDay = dt.toDateString() === now.toDateString()
  const time = dt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  return sameDay ? time : dt.toLocaleDateString([], { month: 'numeric', day: 'numeric' }) + ' ' + time
}

/**
 * Open a settings section by its nav label. The MyWork Codex UI shell handles the
 * `dcu-settings-open-section` event in one commit; dsh's own shell is driven by
 * clicking the trigger and then the nav button with that text.
 */
function openSettingsSection(labels) {
  const trigger = document.querySelector('.dcu-settings-seat [data-dcu-settings-trigger], [data-dcu-settings-trigger], [aria-haspopup="dialog"]')
  if (!trigger) return false
  const ev = new CustomEvent('dcu-settings-open-section', { detail: { labels }, cancelable: true })
  if (!trigger.dispatchEvent(ev)) return true
  if (!document.querySelector('[data-dcu-settings-page],[role="dialog"]')) trigger.click()
  const deadline = Date.now() + 4000
  const tryPick = () => {
    const buttons = [...document.querySelectorAll('[data-dcu-settings-page] nav button,[role="dialog"] nav button')]
    const hit = buttons.find((b) => labels.includes((b.textContent || '').trim()))
    if (hit) { hit.click(); return }
    if (Date.now() < deadline) requestAnimationFrame(tryPick)
  }
  tryPick()
  return true
}

function pad2(n) { return (n < 10 ? '0' : '') + n }
function localDateInput(d) { return d.getFullYear() + '-' + pad2(d.getMonth() + 1) + '-' + pad2(d.getDate()) }
function localTimeInput(d) { return pad2(d.getHours()) + ':' + pad2(d.getMinutes()) }

// ---------------------------------------------------------------------------

exports.name = PLUGIN
exports.inject = ['slots', 'locale', 'layout']

exports.apply = function apply(ctx) {
  ctx.effect(() => injectStyles(), `${PLUGIN}: stylesheet`)
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), `${PLUGIN}: dictionaries`)
  const t = ctx.locale.bind(NS)
  const lang = () => { try { return ctx.locale.getSnapshot().active.toLowerCase().startsWith('zh') ? 'zh' : 'en' } catch { return 'zh' } }
  const dict = () => (lang() === 'zh' ? zh : en)

  // ---- state ---------------------------------------------------------------
  const state = { open: false, tab: 'reminders', items: [], dataPath: '', toasts: [], loaded: false }
  const subs = new Set()
  const emit = () => { subs.forEach((fn) => { try { fn() } catch { /* ignore */ } }) }
  const set = (patch) => { Object.assign(state, patch); emit() }
  function useState(getter) {
    const [v, setV] = React.useState(getter)
    React.useEffect(() => { const fn = () => setV(getter()); subs.add(fn); return () => { subs.delete(fn) } }, [])
    return v
  }

  let inflight = null
  async function refresh() {
    if (inflight) return inflight
    inflight = api('/list').then((d) => { set({ items: d.items || [], dataPath: d.dataPath || '', loaded: true }) })
      .catch((e) => { console.warn(`[${PLUGIN}] list failed`, e) })
      .finally(() => { inflight = null })
    return inflight
  }

  const firing = new Set()
  async function fire(r, due, stale) {
    const key = r.id + '@' + due.toISOString()
    if (firing.has(key)) return
    firing.add(key)
    try {
      // Re-check with the host first so a sibling tab that already fired wins.
      const fresh = await api('/list').catch(() => null)
      const latest = fresh && fresh.items ? fresh.items.find((x) => x.id === r.id) : r
      if (!latest || (latest.lastFiredAt && latest.lastFiredAt >= due.toISOString())) return
      await api('/fired', { id: r.id, at: due.toISOString() })
      if (!stale) {
        const toast = { key, title: r.title, note: r.note, at: due, missed: (Date.now() - due.getTime()) > 90000 }
        set({ toasts: state.toasts.concat([toast]) })
        setTimeout(() => dismiss(key), 60000)
        if (soundEnabled()) beep()
        if (r.im) fetch('/mywork-im/api/send', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ target: r.im === true ? '' : r.im, text: '⏰ ' + r.title + (r.note ? '\n' + r.note : '') }) }).catch((e) => console.warn(`[${PLUGIN}] IM delivery failed`, e))
        try {
          if (typeof Notification !== 'undefined' && Notification.permission === 'granted') {
            const n = new Notification(r.title, { body: (r.note ? r.note + '\n' : '') + fmt(due), tag: key })
            n.onclick = () => { try { window.focus() } catch { /* ignore */ } n.close() }
          }
        } catch { /* ignore */ }
      }
      await refresh()
    } finally { firing.delete(key) }
  }
  function dismiss(key) {
    // Play the exit animation first (180ms), then drop the toast; reduced-motion users see no delay worth noticing.
    if (state.toasts.some((x) => x.key === key && !x.leaving)) { set({ toasts: state.toasts.map((x) => (x.key === key ? { ...x, leaving: true } : x)) }); setTimeout(() => set({ toasts: state.toasts.filter((x) => x.key !== key) }), 180) }
    else set({ toasts: state.toasts.filter((x) => x.key !== key) })
  }

  function tick() {
    const now = new Date()
    for (const r of state.items) {
      const due = logic.dueOccurrence(r, now)
      if (due) fire(r, due.at, due.stale)
    }
  }

  ctx.effect(() => {
    refresh()
    const poll = setInterval(refresh, POLL_MS)
    const tk = setInterval(tick, TICK_MS)
    const onVis = () => { if (document.visibilityState === 'visible') refresh().then(tick) }
    document.addEventListener('visibilitychange', onVis)
    window.addEventListener('focus', onVis)
    return () => { clearInterval(poll); clearInterval(tk); document.removeEventListener('visibilitychange', onVis); window.removeEventListener('focus', onVis) }
  }, `${PLUGIN}: poll & tick`)

  async function add(input) {
    const d = await api('/add', input)
    set({ items: state.items.concat([d.item]) })
  }
  async function update(id, patch) {
    const d = await api('/update', { id, ...patch })
    set({ items: state.items.map((x) => (x.id === id ? d.item : x)) })
  }
  async function remove(id) {
    await api('/remove', { id })
    set({ items: state.items.filter((x) => x.id !== id) })
  }

  // ---- components ---------------------------------------------------------
  const h = React.createElement

  function ToggleButton() {
    const open = useState(() => state.open)
    const count = useState(() => state.items.filter((x) => x.enabled).length)
    return h('button', { type: 'button', className: 'mwr-btn' + (open ? ' active' : ''), title: t('toggle'), onClick: () => { set({ open: !state.open }); if (!state.loaded) refresh() } },
      icon('calendar'), count > 0 ? h('span', { className: 'mwr-badge' }, String(count)) : null)
  }

  function Row(props) {
    const { r } = props
    const [confirm, setConfirm] = React.useState(false)
    React.useEffect(() => { if (!confirm) return undefined; const id = setTimeout(() => setConfirm(false), 6000); return () => clearTimeout(id) }, [confirm])
    const next = logic.nextOccurrence(r, new Date(r.lastFiredAt || r.createdAt || Date.now()))
    const overdue = next && next.getTime() < Date.now()
    return h('div', { className: 'mwr-row' + (r.enabled ? '' : ' off') },
      h('div', { className: 'mwr-main' },
        h('div', { className: 'mwr-title', title: r.title }, r.title),
        h('div', { className: 'mwr-meta' },
          h('span', { className: 'mwr-pill' }, logic.describe(r, lang())),
          r.enabled ? h('span', { className: 'mwr-pill' + (overdue ? ' due' : '') }, (overdue ? t('overdue') : t('next')) + ' · ' + fmt(next)) : null,
          r.im ? h('span', { className: 'mwr-pill' }, 'IM') : null,
        ),
        r.note ? h('div', { className: 'mwr-note' }, r.note) : null,
      ),
      h('div', { className: 'mwr-acts' },
        h('button', { className: 'mwr-mini', title: r.enabled ? t('pause') : t('enable'), onClick: () => update(r.id, { enabled: !r.enabled }) }, r.enabled ? icon('pause', { size: 13 }) : icon('play', { size: 13 })),
        h('button', { className: 'mwr-mini danger', title: confirm ? t('confirm') : t('remove'), 'aria-label': confirm ? t('confirm') : t('remove'), onClick: () => { if (confirm) remove(r.id); else setConfirm(true) } }, confirm ? t('confirm') : icon('x', { size: 13 })),
      ),
    )
  }

  function AddForm() {
    const d = dict()
    const now = new Date()
    const [kind, setKind] = React.useState('once')
    const [title, setTitle] = React.useState('')
    const [note, setNote] = React.useState('')
    const [date, setDate] = React.useState(localDateInput(now))
    const [time, setTime] = React.useState(localTimeInput(new Date(now.getTime() + 10 * 60000)))
    const [days, setDays] = React.useState([1, 2, 3, 4, 5])
    const [every, setEvery] = React.useState(30)
    const [toIm, setToIm] = React.useState(false)
    const [imChats, setImChats] = React.useState([])
    const [imTarget, setImTarget] = React.useState('')
    React.useEffect(() => { fetch('/mywork-im/api/chats').then((r) => r.ok ? r.json() : null).then((d) => { const items = d && d.items ? d.items : []; setImChats(items); if (items.length === 1) setImTarget(items[0].sessionId) }).catch(() => {}) }, [])
    const [err, setErr] = React.useState('')
    const [busy, setBusy] = React.useState(false)
    const submit = async () => {
      setErr('')
      const input = { title, note, kind }
      if (kind === 'once') input.at = new Date(date + 'T' + time + ':00').toISOString()
      if (kind === 'daily' || kind === 'weekly') input.time = time
      if (kind === 'weekly') input.weekdays = days
      if (kind === 'interval') input.everyMinutes = Number(every)
      if (toIm) { if (!imTarget) { setErr(lang() === 'zh' ? '请选择要发到的 IM 聊天' : 'choose the IM chat to notify'); return } input.im = imTarget }
      const n = logic.normalize(input)
      if (!n.ok) { setErr(n.error); return }
      if (kind === 'once' && new Date(input.at).getTime() <= Date.now()) { setErr(lang() === 'zh' ? '时间需要在将来' : 'time must be in the future'); return }
      setBusy(true)
      try { await add(n.value); setTitle(''); setNote('') } catch (e) { setErr(String(e.message || e)) } finally { setBusy(false) }
    }
    const seg = (id, label) => h('button', { type: 'button', className: kind === id ? 'on' : '', onClick: () => setKind(id) }, label)
    return h('div', { className: 'mwr-form' },
      h('input', { className: 'mwr-in', placeholder: d.placeholder, 'aria-label': d.placeholder, value: title, onChange: (e) => setTitle(e.target.value), onKeyDown: (e) => { if (e.key === 'Enter') submit() } }),
      h('div', { className: 'mwr-line' },
        h('div', { className: 'mwr-seg' }, seg('once', d.once), seg('daily', d.daily), seg('weekly', d.weekly), seg('interval', d.interval)),
      ),
      h('div', { className: 'mwr-line' },
        kind === 'once' ? h('input', { className: 'mwr-in', type: 'date', value: date, onChange: (e) => setDate(e.target.value) }) : null,
        kind !== 'interval' ? h('input', { className: 'mwr-in', type: 'time', value: time, onChange: (e) => setTime(e.target.value) }) : null,
        kind === 'interval' ? h('input', { className: 'mwr-in', type: 'number', min: 1, value: every, onChange: (e) => setEvery(e.target.value) }) : null,
        kind === 'interval' ? h('span', null, d.minutes) : null,
        kind === 'weekly' ? h('div', { className: 'mwr-wd' }, [1, 2, 3, 4, 5, 6, 7].map((n) => h('button', { key: n, type: 'button', className: days.includes(n) ? 'on' : '', onClick: () => setDays(days.includes(n) ? days.filter((x) => x !== n) : days.concat([n]).sort()) }, d.weekdays[n - 1]))) : null,
      ),
      h('input', { className: 'mwr-in', placeholder: d.note, 'aria-label': d.note, value: note, onChange: (e) => setNote(e.target.value) }),
      imChats.length ? h('div', { className: 'mwr-line', style: { fontSize: 12 } },
        h('label', { style: { display: 'inline-flex', alignItems: 'center', gap: 6, cursor: 'pointer' } }, h('input', { type: 'checkbox', checked: toIm, onChange: (e) => setToIm(e.target.checked) }), d.toIm),
        toIm ? h('select', { className: 'mwr-in', 'aria-label': d.toIm, style: { flex: 1 }, value: imTarget, onChange: (e) => setImTarget(e.target.value) }, imChats.length === 1 ? null : h('option', { value: '' }, lang() === 'zh' ? '请选择聊天' : 'choose a chat'), imChats.map((c) => h('option', { key: c.sessionId, value: c.sessionId }, `${c.platform} · ${c.channelName} · ${c.title}`))) : null) : null,
      err ? h('div', { className: 'mwr-err' }, err) : null,
      h('div', { className: 'mwr-line' }, h('span', { style: { flex: 1 } }), h('button', { className: 'mwr-primary', disabled: busy || !title.trim(), onClick: submit }, d.add)),
    )
  }

  const automationInstalled = () => {
    try { return ctx.slots.entriesOfSlot('settings.section').some((e) => { const l = typeof e.options.label === 'function' ? e.options.label() : e.options.label; return AUTOMATION_LABELS.includes(String(l || '').trim()) }) } catch { return false }
  }

  /** Prefer the standalone panel (Codex UI fork); fall back to the settings section elsewhere. */
  const openTasks = () => {
    let hasPanel = false
    try { hasPanel = ctx.slots.entriesOfSlot('sidebar.panellist').some((e) => e.options.id === SCHEDULE_PANEL_ID) } catch { hasPanel = false }
    if (hasPanel && ctx.layout && typeof ctx.layout.selectPanel === 'function') { ctx.layout.selectPanel(SCHEDULE_PANEL_ID); return }
    openSettingsSection(AUTOMATION_LABELS)
  }

  /**
   * "运行结束发到 IM" lives INSIDE each scheduled task's own settings.
   * @michengai/dsh-automation has no extension point for its task dialog, so we watch the DOM:
   *   • task dialog  form.dsh-st-modal  → a field (chat + 每次/仅失败) before the 保存/取消 row; saved on submit
   *   • task card    article.dsh-st-card → a chip in the card foot showing the current rule
   * Task identity: Automation's dialog exposes only the name, so the field is bound by name
   * (edit) or by "the task that appears with this name after save" (create). Rules are stored
   * per task id by dsh-mywork-im (POST /mywork-im/api/notify { taskId, target, when }).
   */
  function installNotifyInjector() {
    if (typeof document === 'undefined' || typeof MutationObserver === 'undefined') return
    const NOTIFY_API = '/mywork-im/api/notify'
    let data = null // { config, chats, tasks } | null when dsh-mywork-im is not installed
    let available = true
    const chatLabel = (c) => `${c.platform} · ${c.channelName} · ${c.title}`
    const load = () => fetch(NOTIFY_API).then((r) => { if (r.status === 404) { available = false; return null } return r.ok ? r.json() : null }).then((x) => { if (x) { data = x; decorateCards() } return data }).catch(() => null)
    const post = (body) => fetch(NOTIFY_API, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }).then((r) => r.json()).then((x) => { if (x && x.error) throw new Error(x.error); data = x; decorateCards(); return x })
    const rules = () => (data && data.config && data.config.automation && data.config.automation.tasks) || {}
    const tasksNamed = (name) => (data ? data.tasks : []).filter((x) => x.name === name)

    // ---- cards -------------------------------------------------------------------------
    function decorateCards() {
      if (!data) return
      const d = dict()
      const byId = rules()
      const chats = data.chats || []
      document.querySelectorAll('article.dsh-st-card').forEach((card) => {
        const foot = card.querySelector('.dsh-st-card-foot'); const h3 = card.querySelector('h3')
        if (!foot || !h3) return
        const task = tasksNamed(h3.textContent.trim())[0]
        const rule = task ? byId[task.id] : null
        let chip = foot.querySelector('.mwn-chip')
        if (!rule) { if (chip) chip.remove(); return }
        const chat = chats.find((c) => c.sessionId === rule.target)
        const text = (chat ? `${chat.platform} · ${chat.title}` : d.notifyUnknownChat) + ' · ' + (rule.when === 'failed' ? d.notifyFailed : d.notifyAlways)
        if (!chip) { chip = document.createElement('span'); chip.className = 'dsh-st-chip mwn-chip'; chip.dataset.fresh = '1'; chip.innerHTML = ICON_SEND; chip.appendChild(document.createTextNode('')); foot.insertBefore(chip, foot.firstChild ? foot.firstChild.nextSibling : null) }
        chip.title = d.notifyTitle + '：' + text
        if (chip.lastChild.textContent !== text) { chip.lastChild.textContent = text; if (!chip.dataset.fresh) { chip.classList.remove('mwn-flash'); void chip.offsetWidth; chip.classList.add('mwn-flash') } }
        chip.dataset.fresh = ''
      })
    }

    // ---- dialog ------------------------------------------------------------------------
    function decorateDialog(form) {
      if (form.dataset.mwn) return
      form.dataset.mwn = '1'
      const actions = form.querySelector('.dsh-st-modal-actions')
      const nameInput = form.querySelector('label.dsh-st-field input')
      if (!actions || !nameInput) return
      const d = dict()
      const isEdit = /编辑|edit/i.test((form.querySelector('h2') || {}).textContent || '')
      const knownIds = new Set((data ? data.tasks : []).map((x) => x.id))
      let boundId = ''
      if (isEdit) { const hit = tasksNamed(nameInput.value.trim())[0]; boundId = hit ? hit.id : '' }
      const existing = boundId ? rules()[boundId] : null

      const field = document.createElement('div'); field.className = 'dsh-st-field mwn-field'
      const label = document.createElement('span'); label.textContent = d.notifyTitle
      const row = document.createElement('div'); row.className = 'mwn-row'
      const select = document.createElement('select'); select.className = 'mwn-select'
      const off = document.createElement('option'); off.value = ''; off.textContent = d.notifyOff; select.appendChild(off)
      ;(data ? data.chats : []).forEach((c) => { const o = document.createElement('option'); o.value = c.sessionId; o.textContent = chatLabel(c); select.appendChild(o) })
      select.value = existing ? existing.target : ''
      const seg = document.createElement('div'); seg.className = 'mwr-seg'
      let when = existing ? existing.when : 'always'
      const mk = (v, txt) => { const b = document.createElement('button'); b.type = 'button'; b.textContent = txt; b.onclick = () => { when = v; paint() }; seg.appendChild(b); return b }
      const bAlways = mk('always', d.notifyAlways); const bFailed = mk('failed', d.notifyFailed)
      const paint = () => { bAlways.className = when !== 'failed' ? 'on' : ''; bFailed.className = when === 'failed' ? 'on' : ''; seg.style.display = select.value ? '' : 'none' }
      select.onchange = paint; paint()
      const hint = document.createElement('div'); hint.className = 'mwn-hint'
      hint.textContent = (data && data.chats.length === 0) ? d.notifyNoChats : d.notifyFieldHint
      row.appendChild(select); row.appendChild(seg)
      field.appendChild(label); field.appendChild(row); field.appendChild(hint)
      actions.parentNode.insertBefore(field, actions)

      // Save together with the task: Automation validates + submits the form and closes the dialog on
      // success (a validation error keeps it open, e.g. a one-off time in the past). We arm on submit
      // and write the rule only once the dialog has really gone away, bound to the task's id.
      let armed = null
      const onSubmit = () => {
        const target = select.value; const chosenWhen = target ? when : 'off'
        const unchanged = (!existing && !target) || (existing && existing.target === target && existing.when === chosenWhen)
        armed = unchanged ? null : { target, when: chosenWhen, name: nameInput.value.trim(), at: Date.now() }
      }
      form.addEventListener('submit', onSubmit, true)
      // Dismissing the dialog after a rejected save (取消 / × / Esc / click on the mask) must not write anything.
      const disarm = () => { armed = null }
      form.querySelectorAll('.dsh-st-modal-close, .dsh-st-modal-actions button:not(.dsh-st-btn--primary)').forEach((b) => b.addEventListener('click', disarm, true))
      form.addEventListener('keydown', (e) => { if (e.key === 'Escape') disarm() }, true)
      const mask = form.parentElement
      if (mask && mask.classList.contains('dsh-st-mask')) mask.addEventListener('click', (e) => { if (e.target === mask) disarm() }, true)
      const tick = () => {
        if (form.isConnected) { if (armed && Date.now() - armed.at > 15000) armed = null; return setTimeout(tick, 250) }
        if (!armed) return
        const a = armed; armed = null
        const started = Date.now()
        const tryBind = async () => {
          const fresh = await load()
          let id = boundId
          if (!id && fresh) { const cands = fresh.tasks.filter((x) => x.name === a.name && (isEdit || !knownIds.has(x.id))); if (cands.length) id = cands[0].id }
          if (!id) { if (Date.now() - started < 8000) return setTimeout(tryBind, 600); return }
          await post({ taskId: id, target: a.target, when: a.when })
        }
        tryBind()
      }
      setTimeout(tick, 250)
    }

    const scan = () => {
      if (!available) return
      document.querySelectorAll('form.dsh-st-modal').forEach(decorateDialog)
      decorateCards()
    }
    let pending = 0
    const observer = new MutationObserver(() => { if (pending) return; pending = setTimeout(() => { pending = 0; scan() }, 80) })
    observer.observe(document.body, { childList: true, subtree: true })
    load().then(scan)
    setInterval(() => { if (available && document.querySelector('article.dsh-st-card, form.dsh-st-modal')) load() }, 15000)
  }

  function TasksTab() {
    const installed = automationInstalled()
    return h('div', { className: 'mwr-tasks' },
      h('div', null, t('tasksHint')),
      installed
        ? h('div', null, h('button', { className: 'mwr-primary', onClick: () => { set({ open: false }); openTasks() } }, t('tasksOpen')))
        : h('div', { className: 'mwr-err' }, t('tasksMissing')),
    )
  }

  function Panel() {
    const open = useState(() => state.open)
    const items = useState(() => state.items)
    const tab = useState(() => state.tab)
    if (!open) return null
    const sorted = items.slice().sort((a, b) => {
      const na = logic.nextOccurrence(a, new Date(a.lastFiredAt || a.createdAt || 0)); const nb = logic.nextOccurrence(b, new Date(b.lastFiredAt || b.createdAt || 0))
      if (a.enabled !== b.enabled) return a.enabled ? -1 : 1
      return (na ? na.getTime() : Infinity) - (nb ? nb.getTime() : Infinity)
    })
    const tabBtn = (id, label) => h('button', { type: 'button', role: 'tab', className: 'mwr-tab' + (tab === id ? ' on' : ''), 'aria-selected': tab === id, onClick: () => set({ tab: id }) }, label)
    return h('div', { className: 'mwr-panel', role: 'dialog', 'aria-label': t('title') },
      h('div', { className: 'mwr-head' }, icon('calendar'), t('title'), h('span', { className: 'sp' }), h('button', { className: 'mwr-x', onClick: () => set({ open: false }) }, icon('x', { size: 14 }))),
      h('div', { className: 'mwr-tabs', role: 'tablist' }, tabBtn('reminders', t('reminders')), tabBtn('tasks', t('tasks'))),
      tab === 'tasks'
        ? h(TasksTab)
        : h(React.Fragment, null,
          h('div', { className: 'mwr-list' }, sorted.length === 0 ? h('div', { className: 'mwr-empty' }, t('empty')) : sorted.map((r) => h(Row, { key: r.id, r }))),
          h(AddForm),
        ),
    )
  }

  function Toasts() {
    const toasts = useState(() => state.toasts)
    if (toasts.length === 0) return null
    return h('div', { className: 'mwr-toasts' }, toasts.map((x) => h('div', { className: 'mwr-toast' + (x.leaving ? ' out' : ''), key: x.key },
      h('div', { className: 'ic' }, icon('bell', { size: 18 })),
      h('div', { style: { flex: 1, minWidth: 0 } },
        h('div', { className: 'tt' }, x.title),
        h('div', { className: 'ts' }, t('fired') + ' · ' + fmt(x.at) + (x.missed ? t('missed') : '') + (x.note ? ' · ' + x.note : '')),
      ),
      h('button', { className: 'mwr-primary', onClick: () => dismiss(x.key) }, t('dismiss')),
    )))
  }

  function Overlay() { return h(React.Fragment, null, h(Panel), h(Toasts)) }

  function SettingsSection() {
    const d = dict()
    const [, force] = React.useState(0)
    const items = useState(() => state.items)
    const dataPath = useState(() => state.dataPath)
    const perm = typeof Notification === 'undefined' ? 'na' : Notification.permission
    const permLabel = perm === 'granted' ? d.notifOn : perm === 'denied' ? d.notifDenied : perm === 'na' ? d.notifNA : d.notifOff
    const ask = () => { if (typeof Notification !== 'undefined' && perm === 'default') Notification.requestPermission().then(() => force((n) => n + 1)) }
    const snd = soundEnabled()
    return h('div', { className: 'mwr-set' },
      h('div', { className: 'mwr-hint', style: { color: 'var(--dsw-alias-label-secondary)', lineHeight: 1.6 } }, d.help, ' ', h('code', null, dataPath || '…')),
      h('div', { className: 'row' }, h('span', { className: 'lab' }, d.notif), h('button', { className: 'mwr-mini', style: { border: '0.5px solid var(--dsw-alias-border-l2)' }, onClick: ask }, permLabel)),
      h('div', { className: 'row' }, h('span', { className: 'lab' }, d.sound), h('button', { className: 'mwr-mini', style: { border: '0.5px solid var(--dsw-alias-border-l2)' }, onClick: () => { setSound(!snd); beep(); force((n) => n + 1) } }, snd ? d.on : d.off)),
      h('div', { className: 'row' }, h('span', { className: 'lab' }, d.title), h('button', { className: 'mwr-mini', style: { border: '0.5px solid var(--dsw-alias-border-l2)' }, onClick: () => set({ open: true }) }, d.toggle + ' (' + items.length + ')')),
      h('div', null, items.map((r) => h(Row, { key: r.id, r }))),
    )
  }

  // ---- registrations --------------------------------------------------------
  ctx.slots.inject('conversation.input.right', () => ctx.slots.register({
    name: 'conversation.input.right', id: PLUGIN, order: 40,
  }, function MyworkScheduleButton() { return h(ToggleButton) }))

  ctx.slots.inject('shell.overlay', () => ctx.slots.register({
    name: 'shell.overlay', id: PLUGIN, order: 40,
  }, function MyworkScheduleOverlay() { return h(Overlay) }))

  installNotifyInjector()

  // "日程" tab inside Settings → MyWork (slot declared by dsh-mywork-kit).
  ctx.slots.inject(TAB_SLOT, () => ctx.slots.register({
    name: TAB_SLOT, id: 'schedule', order: 30, label: () => t('nav'),
  }, function MyworkScheduleTab() { return h(SettingsSection) }))
}

    return module.exports;
  }
});
