#!/usr/bin/env node
/**
 * Shared client-bundle builder for the MyWork Kit packages (zero dependencies).
 *
 * DSH web plugins ship their browser half as a "C6" bundle: a script that calls
 * `window.__ModuleLoader__.load({ id, factory })`, where `factory(require)` is a
 * lazy CommonJS module and `react` is a platform module supplied by DSH.
 *
 * Usage (from a package directory):  node ../../scripts/build-client.mjs
 *   reads  <pkg>/src/client/index.js   (plain CommonJS, may `require('react')`)
 *   plus   package.json "mywork": { "clientPrelude": ["src/logic.cjs"] } — pure
 *          CommonJS modules inlined BEFORE the client source; each prelude is
 *          wrapped so its `module.exports` lands in `__prelude['<file>']`, and
 *          the client reads it via `require('./<file>')`.
 *   writes <pkg>/lib/client.js
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const pkgDir = resolve(process.argv[2] ?? process.cwd())
const pkg = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'))
const source = readFileSync(join(pkgDir, 'src', 'client', 'index.js'), 'utf8')
const preludes = (pkg.mywork && Array.isArray(pkg.mywork.clientPrelude)) ? pkg.mywork.clientPrelude : []
let preludeCode = ''
if (preludes.length > 0) {
  preludeCode += '    var __prelude = {};\n'
  preludeCode += '    var __hostRequire = require;\n'
  preludeCode += '    require = function (id) { var k = String(id).replace(/^\\.\\//, "").replace(/^src\\//, ""); if (Object.prototype.hasOwnProperty.call(__prelude, k)) return __prelude[k]; var base = k.split("/").pop(); if (Object.prototype.hasOwnProperty.call(__prelude, base)) return __prelude[base]; return __hostRequire(id); };\n'
  for (const rel of preludes) {
    const code = readFileSync(join(pkgDir, rel), 'utf8')
    const key = rel.split('/').pop()
    preludeCode += `    __prelude[${JSON.stringify(key)}] = (function () { var module = { exports: {} }; var exports = module.exports;\n${code}\n    return module.exports; })();\n`
  }
}
const banner = `/* Generated by scripts/build-client.mjs from src/client/index.js — do not edit by hand. */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(pkg.name)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
`
const footer = `
    return module.exports;
  }
});
`
mkdirSync(join(pkgDir, 'lib'), { recursive: true })
writeFileSync(join(pkgDir, 'lib', 'client.js'), banner + preludeCode + source + footer)
console.log(`[build-client] ${pkg.name}: lib/client.js (${source.length} source bytes)`)
