/* Generated by scripts/build-client.mjs from src/client/index.js — do not edit by hand. */
window.__ModuleLoader__.load({
  id: "dsh-mywork-shell",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
/**
 * dsh-mywork-shell — browser half (CommonJS; wrapped into a DSH client bundle
 * by scripts/build-client.mjs).
 *
 *   1. Theme families over dsh's own light / dark palettes through the official
 *      `ctx.theme.overrideTokens` layer API:
 *        claude — warm ivory + Claude orange accent
 *        codex  — neutral monochrome, terminal feel
 *      The family is remembered in this browser; the light/dark/system scheme
 *      is stored by dsh itself, so the two combine freely.
 *   2. UI zoom (80–150 %). CSS `zoom` goes on #root, NOT on <html>: dsh positions its
 *      floating menus (workspace / mode / model pickers, tooltips) with viewport
 *      coordinates from getBoundingClientRect() and portals them to <body>; inside a
 *      zoomed <html> those coordinates land 10 % off. Portals therefore stay unzoomed
 *      and only their content is scaled (see the .mywork-zoom rules in CSS).
 *   3. One "外观 / Appearance" tab inside the MyWork settings section (the tab
 *      slot `mywork.settings.tab` is declared by dsh-mywork-kit).
 *
 * The sidebar itself comes from dsh-mywork-codex-ui. Nothing here patches dsh:
 * unloading the plugin removes the override layer, the CSS and the tab.
 */
'use strict'

const React = require('react')

const PLUGIN = 'dsh-mywork-shell'
const NS = 'mywork.shell'
const STORAGE_KEY = 'dsh-mywork-shell:theme'
const TAB_SLOT = 'mywork.settings.tab'

// ---------------------------------------------------------------------------
// Palettes (alias-token overrides; every value is a plain CSS color).
// Token names come from @deepseek-ai/dsh-client-ui-theme design-platform.css.
// ---------------------------------------------------------------------------

const CLAUDE_LIGHT = {
  '--dsw-alias-bg-base': '#F4F3EE',
  '--dsw-alias-bg-layer-1': '#FBFAF7',
  '--dsw-alias-bg-layer-2': '#EFEDE6',
  '--dsw-alias-bg-layer-3': '#E7E4DB',
  '--dsw-alias-bg-overlay': '#FFFFFF',
  '--dsw-alias-bg-mask-1': 'rgba(31, 30, 29, 0.35)',
  '--dsw-alias-border-l1': 'rgba(31, 30, 29, 0.06)',
  '--dsw-alias-border-l2': 'rgba(31, 30, 29, 0.11)',
  '--dsw-alias-border-l3': 'rgba(31, 30, 29, 0.18)',
  '--dsw-alias-brand-primary': '#D97757',
  '--dsw-alias-brand-text': '#A75437',
  '--dsw-alias-link': '#A75437',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary': '#1F1E1D',
  '--dsw-alias-label-secondary': '#5B5852',
  '--dsw-alias-label-tertiary': '#67645E',
  '--dsw-alias-label-caption': '#706D66',
  '--dsw-alias-button-primary-fill': '#BA5A3A',
  '--dsw-alias-button-primary-hover': '#A84D2C',
  '--dsw-alias-interactive-bg-hover': 'rgba(31, 30, 29, 0.05)',
  '--dsw-alias-interactive-bg-active': 'rgba(31, 30, 29, 0.09)',
  '--dsw-alias-markdown-code-block': '#EEEBE3',
  '--dsw-alias-markdown-code-block-banner': '#E5E1D6',
  '--dsw-alias-markdown-inline-code': '#ECE8DF',
  '--dsw-specific-sidebar-fill': '#E8E1CF',
  '--dsw-alias-state-success-primary': '#4A7249',
  '--dsw-alias-state-warn-primary': '#8B692A',
  '--dsw-alias-state-error-primary': '#B84E38',
  // surfaces dsh draws with "specific" tokens (user bubble, composer) and its blue "business" accent (active tab, send button, drop targets)
  '--dsw-specific-bubble': '#EFE8D8',
  '--dsw-specific-input-major': '#FFFFFF',
  '--dsw-alias-state-business-primary': '#A75437',
  '--dsw-alias-button-info-fill': '#BA5A3A',
  '--dsw-alias-button-info-hover': '#A84D2C',
}

const CLAUDE_DARK = {
  '--dsw-alias-bg-base': '#262624',
  '--dsw-alias-bg-layer-1': '#2E2E2B',
  '--dsw-alias-bg-layer-2': '#383734',
  '--dsw-alias-bg-layer-3': '#42413D',
  '--dsw-alias-bg-overlay': '#30302D',
  '--dsw-alias-bg-mask-1': 'rgba(0, 0, 0, 0.5)',
  '--dsw-alias-border-l1': 'rgba(255, 255, 255, 0.07)',
  '--dsw-alias-border-l2': 'rgba(255, 255, 255, 0.12)',
  '--dsw-alias-border-l3': 'rgba(255, 255, 255, 0.2)',
  '--dsw-alias-brand-primary': '#D97757',
  '--dsw-alias-brand-text': '#E8916F',
  '--dsw-alias-link': '#E8916F',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary': '#EDECE8',
  '--dsw-alias-label-secondary': '#A8A59E',
  '--dsw-alias-label-tertiary': '#9A9791',
  '--dsw-alias-label-caption': '#8F8D88',
  '--dsw-alias-button-primary-fill': '#BA5A3A',
  '--dsw-alias-button-primary-hover': '#E8916F',
  '--dsw-alias-interactive-bg-hover': 'rgba(255, 255, 255, 0.06)',
  '--dsw-alias-interactive-bg-active': 'rgba(255, 255, 255, 0.1)',
  '--dsw-alias-markdown-code-block': '#1F1F1D',
  '--dsw-alias-markdown-code-block-banner': '#1A1A18',
  '--dsw-alias-markdown-inline-code': '#3A3936',
  '--dsw-specific-sidebar-fill': '#1C1915',
  '--dsw-alias-state-success-primary': '#7FB77E',
  '--dsw-alias-state-warn-primary': '#E0B458',
  '--dsw-alias-state-error-primary': '#E68674',
  // surfaces dsh draws with "specific" tokens (user bubble, composer) and its blue "business" accent (active tab, send button, drop targets)
  '--dsw-specific-bubble': '#3B3934',
  '--dsw-specific-input-major': '#30302D',
  '--dsw-alias-state-business-primary': '#E8916F',
  '--dsw-alias-button-info-fill': '#BA5A3A',
  '--dsw-alias-button-info-hover': '#E8916F',
}

/* The three families below come from the taste-skill pack (github.com/Leonxlnx/taste-skill): soft-skill, minimalist-skill,
   brutalist-skill. Each is one override layer with both palettes; every text role was checked against WCAG AA 4.5:1 at build time. */
const SOFT_LIGHT = {
  '--dsw-alias-bg-base': '#F5F5F7',
  '--dsw-alias-bg-layer-1': '#FFFFFF',
  '--dsw-alias-bg-layer-2': '#ECECF1',
  '--dsw-alias-bg-layer-3': '#E2E2EA',
  '--dsw-alias-bg-overlay': '#FFFFFF',
  '--dsw-alias-bg-mask-1': 'rgba(23,23,28,0.4)',
  '--dsw-alias-border-l1': 'rgba(23,23,28,0.05)',
  '--dsw-alias-border-l2': 'rgba(23,23,28,0.09)',
  '--dsw-alias-border-l3': 'rgba(23,23,28,0.16)',
  '--dsw-alias-brand-primary': '#4F46E5',
  '--dsw-alias-brand-text': '#4338CA',
  '--dsw-alias-link': '#4338CA',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary': '#17171C',
  '--dsw-alias-label-secondary': '#5C5C66',
  '--dsw-alias-label-tertiary': '#62626E',
  '--dsw-alias-label-caption': '#62626E',
  '--dsw-alias-label-primary-inverted': '#FFFFFF',
  '--dsw-alias-button-primary-fill': '#4F46E5',
  '--dsw-alias-button-primary-hover': '#4338CA',
  '--dsw-alias-interactive-bg-hover': 'rgba(23,23,28,0.045)',
  '--dsw-alias-interactive-bg-active': 'rgba(23,23,28,0.08)',
  '--dsw-alias-markdown-code-block': '#ECECF1',
  '--dsw-alias-markdown-code-block-banner': '#E2E2EA',
  '--dsw-alias-markdown-inline-code': '#E7E7EE',
  '--dsw-specific-sidebar-fill': '#EDEDF2',
  '--dsw-alias-state-success-primary': '#166534',
  '--dsw-alias-state-warn-primary': '#854D0E',
  '--dsw-alias-state-error-primary': '#B91C1C',
  '--dsw-specific-bubble': '#E9E8FA',
  '--dsw-specific-input-major': '#FFFFFF',
  '--dsw-alias-state-business-primary': '#4F46E5',
  '--dsw-alias-button-info-fill': '#4F46E5',
  '--dsw-alias-button-info-hover': '#4338CA',
}

const SOFT_DARK = {
  '--dsw-alias-bg-base': '#050505',
  '--dsw-alias-bg-layer-1': '#111113',
  '--dsw-alias-bg-layer-2': '#161618',
  '--dsw-alias-bg-layer-3': '#1E1E22',
  '--dsw-alias-bg-overlay': '#111113',
  '--dsw-alias-bg-mask-1': 'rgba(0,0,0,0.7)',
  '--dsw-alias-border-l1': 'rgba(255,255,255,0.06)',
  '--dsw-alias-border-l2': 'rgba(255,255,255,0.10)',
  '--dsw-alias-border-l3': 'rgba(255,255,255,0.18)',
  '--dsw-alias-brand-primary': '#818CF8',
  '--dsw-alias-brand-text': '#A5B4FC',
  '--dsw-alias-link': '#A5B4FC',
  '--dsw-alias-label-primary-foreground': '#0B0B14',
  '--dsw-alias-label-primary': '#F4F4F5',
  '--dsw-alias-label-secondary': '#A1A1AA',
  '--dsw-alias-label-tertiary': '#8E8E98',
  '--dsw-alias-label-caption': '#84848E',
  '--dsw-alias-label-primary-inverted': '#0B0B14',
  '--dsw-alias-button-primary-fill': '#818CF8',
  '--dsw-alias-button-primary-hover': '#A5B4FC',
  '--dsw-alias-interactive-bg-hover': 'rgba(255,255,255,0.06)',
  '--dsw-alias-interactive-bg-active': 'rgba(255,255,255,0.11)',
  '--dsw-alias-markdown-code-block': '#0C0C0E',
  '--dsw-alias-markdown-code-block-banner': '#050505',
  '--dsw-alias-markdown-inline-code': '#1E1E22',
  '--dsw-specific-sidebar-fill': '#0A0A0B',
  '--dsw-alias-state-success-primary': '#34D399',
  '--dsw-alias-state-warn-primary': '#FBBF24',
  '--dsw-alias-state-error-primary': '#F87171',
  '--dsw-specific-bubble': '#17172A',
  '--dsw-specific-input-major': '#111113',
  '--dsw-alias-state-business-primary': '#818CF8',
  '--dsw-alias-button-info-fill': '#818CF8',
  '--dsw-alias-button-info-hover': '#A5B4FC',
}

const MINIMAL_LIGHT = {
  '--dsw-alias-bg-base': '#F7F6F3',
  '--dsw-alias-bg-layer-1': '#FFFFFF',
  '--dsw-alias-bg-layer-2': '#EFEEEA',
  '--dsw-alias-bg-layer-3': '#E6E5E0',
  '--dsw-alias-bg-overlay': '#FFFFFF',
  '--dsw-alias-bg-mask-1': 'rgba(17,17,17,0.35)',
  '--dsw-alias-border-l1': '#F0EFEB',
  '--dsw-alias-border-l2': '#EAEAEA',
  '--dsw-alias-border-l3': '#DAD9D4',
  '--dsw-alias-brand-primary': '#111111',
  '--dsw-alias-brand-text': '#111111',
  '--dsw-alias-link': '#1F6C9F',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary': '#111111',
  '--dsw-alias-label-secondary': '#63625E',
  '--dsw-alias-label-tertiary': '#66655F',
  '--dsw-alias-label-caption': '#66655F',
  '--dsw-alias-label-primary-inverted': '#FFFFFF',
  '--dsw-alias-button-primary-fill': '#111111',
  '--dsw-alias-button-primary-hover': '#333333',
  '--dsw-alias-interactive-bg-hover': 'rgba(17,17,17,0.04)',
  '--dsw-alias-interactive-bg-active': 'rgba(17,17,17,0.08)',
  '--dsw-alias-markdown-code-block': '#F7F6F3',
  '--dsw-alias-markdown-code-block-banner': '#EFEEEA',
  '--dsw-alias-markdown-inline-code': '#F1F0EC',
  '--dsw-specific-sidebar-fill': '#F1F0EC',
  '--dsw-alias-state-success-primary': '#346538',
  '--dsw-alias-state-warn-primary': '#8A5C00',
  '--dsw-alias-state-error-primary': '#9F2F2D',
  '--dsw-specific-bubble': '#F1F0EC',
  '--dsw-specific-input-major': '#FFFFFF',
  '--dsw-alias-state-business-primary': '#111111',
  '--dsw-alias-button-info-fill': '#111111',
  '--dsw-alias-button-info-hover': '#333333',
}

const MINIMAL_DARK = {
  '--dsw-alias-bg-base': '#191919',
  '--dsw-alias-bg-layer-1': '#202020',
  '--dsw-alias-bg-layer-2': '#262626',
  '--dsw-alias-bg-layer-3': '#2E2E2E',
  '--dsw-alias-bg-overlay': '#202020',
  '--dsw-alias-bg-mask-1': 'rgba(0,0,0,0.6)',
  '--dsw-alias-border-l1': 'rgba(232,230,225,0.07)',
  '--dsw-alias-border-l2': 'rgba(232,230,225,0.12)',
  '--dsw-alias-border-l3': 'rgba(232,230,225,0.22)',
  '--dsw-alias-brand-primary': '#E8E6E1',
  '--dsw-alias-brand-text': '#E8E6E1',
  '--dsw-alias-link': '#8DC1E8',
  '--dsw-alias-label-primary-foreground': '#111111',
  '--dsw-alias-label-primary': '#E8E6E1',
  '--dsw-alias-label-secondary': '#A3A19B',
  '--dsw-alias-label-tertiary': '#96948E',
  '--dsw-alias-label-caption': '#8E8C86',
  '--dsw-alias-label-primary-inverted': '#111111',
  '--dsw-alias-button-primary-fill': '#E8E6E1',
  '--dsw-alias-button-primary-hover': '#FFFFFF',
  '--dsw-alias-interactive-bg-hover': 'rgba(232,230,225,0.06)',
  '--dsw-alias-interactive-bg-active': 'rgba(232,230,225,0.12)',
  '--dsw-alias-markdown-code-block': '#111111',
  '--dsw-alias-markdown-code-block-banner': '#0D0D0D',
  '--dsw-alias-markdown-inline-code': '#2E2E2E',
  '--dsw-specific-sidebar-fill': '#141414',
  '--dsw-alias-state-success-primary': '#86C48A',
  '--dsw-alias-state-warn-primary': '#E0B458',
  '--dsw-alias-state-error-primary': '#F0908C',
  '--dsw-specific-bubble': '#262626',
  '--dsw-specific-input-major': '#202020',
  '--dsw-alias-state-business-primary': '#E8E6E1',
  '--dsw-alias-button-info-fill': '#E8E6E1',
  '--dsw-alias-button-info-hover': '#FFFFFF',
}

const BRUTAL_LIGHT = {
  '--dsw-alias-bg-base': '#F4F4F0',
  '--dsw-alias-bg-layer-1': '#FFFFFF',
  '--dsw-alias-bg-layer-2': '#E8E8E2',
  '--dsw-alias-bg-layer-3': '#DCDCD4',
  '--dsw-alias-bg-overlay': '#FFFFFF',
  '--dsw-alias-bg-mask-1': 'rgba(17,17,17,0.5)',
  '--dsw-alias-border-l1': '#C9C9C1',
  '--dsw-alias-border-l2': '#111111',
  '--dsw-alias-border-l3': '#111111',
  '--dsw-alias-brand-primary': '#D41616',
  '--dsw-alias-brand-text': '#B91111',
  '--dsw-alias-link': '#B91111',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary': '#111111',
  '--dsw-alias-label-secondary': '#4A4A4A',
  '--dsw-alias-label-tertiary': '#5E5E5E',
  '--dsw-alias-label-caption': '#626262',
  '--dsw-alias-label-primary-inverted': '#FFFFFF',
  '--dsw-alias-button-primary-fill': '#111111',
  '--dsw-alias-button-primary-hover': '#D41616',
  '--dsw-alias-interactive-bg-hover': 'rgba(17,17,17,0.06)',
  '--dsw-alias-interactive-bg-active': 'rgba(17,17,17,0.12)',
  '--dsw-alias-markdown-code-block': '#111111',
  '--dsw-alias-markdown-code-block-banner': '#050505',
  '--dsw-alias-markdown-inline-code': '#E8E8E2',
  '--dsw-specific-sidebar-fill': '#EAE8E3',
  '--dsw-alias-state-success-primary': '#1F6B2A',
  '--dsw-alias-state-warn-primary': '#8A5A00',
  '--dsw-alias-state-error-primary': '#C41414',
  '--dsw-specific-bubble': '#E8E8E2',
  '--dsw-specific-input-major': '#FFFFFF',
  '--dsw-alias-state-business-primary': '#D41616',
  '--dsw-alias-button-info-fill': '#111111',
  '--dsw-alias-button-info-hover': '#D41616',
}

const BRUTAL_DARK = {
  '--dsw-alias-bg-base': '#0A0A0A',
  '--dsw-alias-bg-layer-1': '#121212',
  '--dsw-alias-bg-layer-2': '#1A1A1A',
  '--dsw-alias-bg-layer-3': '#222222',
  '--dsw-alias-bg-overlay': '#121212',
  '--dsw-alias-bg-mask-1': 'rgba(0,0,0,0.75)',
  '--dsw-alias-border-l1': '#2A2A2A',
  '--dsw-alias-border-l2': '#3A3A3A',
  '--dsw-alias-border-l3': '#EAEAEA',
  '--dsw-alias-brand-primary': '#FF2A2A',
  '--dsw-alias-brand-text': '#FF6B6B',
  '--dsw-alias-link': '#FF6B6B',
  '--dsw-alias-label-primary-foreground': '#0A0A0A',
  '--dsw-alias-label-primary': '#EAEAEA',
  '--dsw-alias-label-secondary': '#B0B0B0',
  '--dsw-alias-label-tertiary': '#9A9A9A',
  '--dsw-alias-label-caption': '#909090',
  '--dsw-alias-label-primary-inverted': '#0A0A0A',
  '--dsw-alias-button-primary-fill': '#EAEAEA',
  '--dsw-alias-button-primary-hover': '#FF2A2A',
  '--dsw-alias-interactive-bg-hover': 'rgba(234,234,234,0.07)',
  '--dsw-alias-interactive-bg-active': 'rgba(234,234,234,0.14)',
  '--dsw-alias-markdown-code-block': '#050505',
  '--dsw-alias-markdown-code-block-banner': '#000000',
  '--dsw-alias-markdown-inline-code': '#222222',
  '--dsw-specific-sidebar-fill': '#0E0E0E',
  '--dsw-alias-state-success-primary': '#4AF626',
  '--dsw-alias-state-warn-primary': '#F2C94C',
  '--dsw-alias-state-error-primary': '#FF6B6B',
  '--dsw-specific-bubble': '#1A1A1A',
  '--dsw-specific-input-major': '#121212',
  '--dsw-alias-state-business-primary': '#FF2A2A',
  '--dsw-alias-button-info-fill': '#EAEAEA',
  '--dsw-alias-button-info-hover': '#FF2A2A',
}

/**
 * Theme families. Each family is one override layer with BOTH palettes, so
 * it follows the host's light / dark / system preference (which dsh itself
 * persists) instead of fighting it. `official` means "no override".
 */
const FAMILIES = [
  { id: 'official', light: null, dark: null, label: { zh: '官方默认', en: 'Official' } },
  { id: 'claude', light: CLAUDE_LIGHT, dark: CLAUDE_DARK, label: { zh: 'Claude Code 风格', en: 'Claude Code style' } },
  { id: 'soft', light: SOFT_LIGHT, dark: SOFT_DARK, label: { zh: '柔和高级', en: 'Soft premium' }, fonts: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Noto+Sans+SC:wght@400;500;600;700&family=Geist+Mono:wght@400;500&display=swap' },
  { id: 'minimal', light: MINIMAL_LIGHT, dark: MINIMAL_DARK, label: { zh: '极简编辑', en: 'Editorial minimal' }, fonts: 'https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600&family=Newsreader:opsz,wght@6..72,400;6..72,500&family=Noto+Sans+SC:wght@400;500;600&family=Noto+Serif+SC:wght@500;600&family=Geist+Mono:wght@400;500&display=swap' },
  { id: 'brutal', light: BRUTAL_LIGHT, dark: BRUTAL_DARK, label: { zh: '工业粗野', en: 'Industrial brutalist' }, fonts: 'https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;800;900&family=JetBrains+Mono:wght@400;500;700&display=swap' },
]

/** Family used until the user picks one (the kit's own look). */
const DEFAULT_FAMILY = 'claude'

const SCHEMES = [
  { id: 'system', label: { zh: '跟随系统', en: 'System' } },
  { id: 'light', label: { zh: '浅色', en: 'Light' } },
  { id: 'dark', label: { zh: '深色', en: 'Dark' } },
]

/** Build the {light, dark} override map the theme service validates. */
function overridesFor(fam) {
  if (!fam || !fam.light) return null
  const names = new Set([...Object.keys(fam.light), ...Object.keys(fam.dark)])
  const out = {}
  for (const n of names) out[n] = { light: fam.light[n] || fam.dark[n], dark: fam.dark[n] || fam.light[n] }
  return out
}

// ---------------------------------------------------------------------------
// Extra CSS keyed by body[data-mywork-theme]. Uses only alias tokens so it
// follows whichever palette is active; kept small on purpose.
// ---------------------------------------------------------------------------

const CSS = `
/* UI zoom: the app root is zoomed; body-level portals keep their coordinates and scale their content. */
#root{zoom:var(--mywork-zoom,1)}
body>:where(:not(#root):not(script):not(style):not(link)){zoom:var(--mywork-zoom,1)}
body>[style*="top:"],body>[style*="left:"],body>[style*="translate"]{zoom:1}
body>[style*="top:"]>*,body>[style*="left:"]>*,body>[style*="translate"]>*{zoom:var(--mywork-zoom,1)}
/* Fixed elements INSIDE the zoomed root that JS positions from getBoundingClientRect()/innerWidth (viewport px):
   the fork's hover cards and portal tool menus, Automation's dropdowns, any React inline "position: fixed".
   An inverse zoom on the element cancels the scaling of its insets, so it lands where the code meant it
   (its content then renders at 100 %, which is fine for a popover). */
#root [style*="position: fixed"], #root .dcu-wb-tip, #root [data-dcu-tool-menu="portal"] { zoom: calc(1 / var(--mywork-zoom, 1)); }
/* dsh-univer-office's floating window is a body-level overlay that moves/resizes itself with pointer deltas
   in viewport px and clamps to window.innerWidth/Height; inside a zoomed overlay those deltas are off by the
   zoom factor (the window lags the cursor). Keep that overlay at zoom 1 (its viewer renders at 100 %). */
body > .uvf_root.uvf_root, body > .uvf_root.uvf_root > * { zoom: 1 !important; }
/* dsh 0.1.6-alpha.2: items hidden inside a collapsed tool-call group keep their 14px flex gap → blank band. */
[class*="_flowItem"][hidden]{display:none!important}
/* shared touches */
body[data-mywork-theme] {
  --mywork-mono: ui-monospace, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
}
body[data-mywork-theme] pre, body[data-mywork-theme] code, body[data-mywork-theme] kbd {
  font-family: var(--mywork-mono);
}
/* Claude: warm accent focus ring + slightly rounder surfaces */
body[data-mywork-theme="claude"] :focus-visible {
  outline: 2px solid color-mix(in srgb, var(--dsw-alias-brand-primary) 70%, transparent);
  outline-offset: 2px;
}
body[data-mywork-theme="claude"] textarea:focus, body[data-mywork-theme="claude"] input:focus {
  outline-color: color-mix(in srgb, var(--dsw-alias-brand-primary) 60%, transparent);
}
body[data-mywork-theme="claude"] a { text-decoration-color: color-mix(in srgb, var(--dsw-alias-brand-primary) 50%, transparent); }
/* Codex: monospace composer and tighter, terminal-like blocks */
body[data-mywork-theme="codex"] textarea { font-family: var(--mywork-mono); font-size: 0.95em; }
body[data-mywork-theme="codex"] pre { border: 0.5px solid var(--dsw-alias-border-l2); }
body[data-mywork-theme="codex"] :focus-visible {
  outline: 1.5px solid var(--dsw-alias-label-primary);
  outline-offset: 1px;
}
/* The Codex UI fork hardcodes its sidebar / settings-page palette (mint grey). Under a family, route those
   variables to the family's tokens so the whole chrome follows the style, not just the chat area. */
body[data-mywork-theme][data-mywork-theme] .dcu-root { /* doubled attribute: outranks the fork's own dark-mode rule */
  --dcu-sidebar-background: var(--dsw-specific-sidebar-fill); --dcu-sidebar-primary: var(--dsw-alias-label-primary);
  --dcu-sidebar-secondary: var(--dsw-alias-label-secondary); --dcu-sidebar-tertiary: var(--dsw-alias-label-tertiary);
  --dcu-sidebar-navigation: var(--dsw-alias-label-primary); --dcu-sidebar-icon: var(--dsw-alias-label-secondary);
  --dcu-sidebar-hover: var(--dsw-alias-interactive-bg-active); --dcu-sidebar-border: var(--dsw-alias-border-l2);
  --dcu-tip-bg: var(--dsw-alias-bg-overlay);
  /* The fork hardcodes Inter for the sidebar; under a family the sidebar uses the same font as the rest of the app (families with their own font override this below). */
  --dcu-font: var(--dsw-font-family, -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif);
}
body[data-mywork-theme][data-mywork-theme] .dcu-settings-page {
  --sp-bg: var(--dsw-alias-bg-base); --sp-nav: var(--dsw-specific-sidebar-fill); --sp-card: var(--dsw-alias-bg-layer-1);
  --sp-border: var(--dsw-alias-border-l2); --sp-text: var(--dsw-alias-label-primary); --sp-muted: var(--dsw-alias-label-secondary);
  --dcu-sidebar-primary: var(--dsw-alias-label-primary); --dcu-sidebar-secondary: var(--dsw-alias-label-secondary); --dcu-sidebar-tertiary: var(--dsw-alias-label-tertiary);
  --sp-hover: var(--dsw-alias-interactive-bg-hover); --sp-active: var(--dsw-alias-interactive-bg-active);
  --dcu-font: var(--dsw-font-family, -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif);
}
@media (prefers-reduced-motion: reduce) { body[data-mywork-theme="tech"] * { transition-duration: 0.01ms !important; animation-duration: 0.01ms !important; } }

/* 柔和高级 (soft-skill "Soft Structuralism / Ethereal Glass"): Plus Jakarta Sans + Geist Mono, squircle radii, ultra-diffuse ambient
   shadows in light, white/10 hairlines in dark, pill primary buttons, spring-like easing. */
body[data-mywork-theme="soft"] {
  --mywork-mono: "Geist Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  --mywork-ease: cubic-bezier(0.32, 0.72, 0, 1);
  --mywork-shadow: 0 1px 2px rgba(23, 23, 28, 0.04), 0 24px 48px -24px rgba(23, 23, 28, 0.22);
  font-family: "Plus Jakarta Sans", "Yuanti SC", "Noto Sans SC", "Microsoft YaHei UI", "Microsoft YaHei", "PingFang SC", sans-serif;
}
body[data-ds-dark-theme][data-mywork-theme="soft"] { --mywork-shadow: 0 0 0 1px rgba(255, 255, 255, 0.08), 0 24px 48px -24px rgba(0, 0, 0, 0.8); }
body[data-mywork-theme="soft"] button, body[data-mywork-theme="soft"] input, body[data-mywork-theme="soft"] select, body[data-mywork-theme="soft"] textarea { font-family: inherit; }
body[data-mywork-theme="soft"][data-mywork-theme] .dcu-root, body[data-mywork-theme="soft"][data-mywork-theme] .dcu-settings-page { --dcu-font: "Plus Jakarta Sans", "Yuanti SC", "Noto Sans SC", "Microsoft YaHei UI", "Microsoft YaHei", "PingFang SC", sans-serif; }
body[data-mywork-theme="soft"] [data-composer-card] { border-radius: 24px !important; box-shadow: var(--mywork-shadow) !important; }
body[data-mywork-theme="soft"] .dcu-home-card { border-radius: 24px; background: var(--dsw-alias-bg-layer-1); box-shadow: var(--mywork-shadow); border-color: transparent; }
body[data-mywork-theme="soft"] .dcu-home-card:hover, body[data-mywork-theme="soft"] .dcu-home-card[aria-pressed=true] { transform: translateY(-2px); border-color: transparent; }
body[data-mywork-theme="soft"] .dcu-home-task, body[data-mywork-theme="soft"] .mwtc-card, body[data-mywork-theme="soft"] .mwi, body[data-mywork-theme="soft"] .dsh-st-card, body[data-mywork-theme="soft"] .ima-platform, body[data-mywork-theme="soft"] .dcu-panel-body > div > div { border-radius: 16px; }
body[data-mywork-theme="soft"] [data-composer-card] [class*="_primary"], body[data-mywork-theme="soft"] .dsh-st-btn--primary, body[data-mywork-theme="soft"] .mwm-primary, body[data-mywork-theme="soft"] .mwi .btn { border-radius: 999px !important; color: var(--dsw-alias-label-primary-foreground) !important; box-shadow: 0 8px 20px -10px var(--dsw-alias-brand-primary); }
body[data-mywork-theme="soft"] .mwb-omni .mwb-in, body[data-mywork-theme="soft"] .dcu-settings-search { border-radius: 999px; }
body[data-mywork-theme="soft"] .dcu-wb-session, body[data-mywork-theme="soft"] .dcu-menu button, body[data-mywork-theme="soft"] .dcu-settings-link { border-radius: 12px; }
body[data-mywork-theme="soft"] button, body[data-mywork-theme="soft"] [role="button"], body[data-mywork-theme="soft"] a, body[data-mywork-theme="soft"] .dcu-home-card { transition: background-color 400ms var(--mywork-ease), border-color 400ms var(--mywork-ease), color 400ms var(--mywork-ease), box-shadow 400ms var(--mywork-ease), transform 400ms var(--mywork-ease); }
body[data-mywork-theme="soft"] button:active { transform: scale(0.98); }
body[data-mywork-theme="soft"] :focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 3px; border-radius: 12px; }
body[data-mywork-theme="soft"] .dcu-wb-section-label, body[data-mywork-theme="soft"] .mwtc-title, body[data-mywork-theme="soft"] .dcu-settings-group-label { letter-spacing: 0.14em; text-transform: uppercase; font-size: 12px; font-weight: 500; }
body[data-mywork-theme="soft"] h1, body[data-mywork-theme="soft"] h2, body[data-mywork-theme="soft"] h3 { letter-spacing: -0.02em; }

/* 极简编辑 (minimalist-skill "Premium Utilitarian Minimalism"): warm bone canvas, exactly 1px #EAEAEA borders, radii ≤ 8px, no shadows,
   Geist UI + Newsreader serif headline + Geist Mono, solid off-black primary button, invisible motion. */
body[data-mywork-theme="minimal"] {
  --mywork-mono: "Geist Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  --mywork-serif: "Newsreader", "Noto Serif SC", "Songti SC", "STSong", "SimSun", Georgia, serif;
  font-family: "Geist", "Noto Sans SC", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
}
body[data-mywork-theme="minimal"] button, body[data-mywork-theme="minimal"] input, body[data-mywork-theme="minimal"] select, body[data-mywork-theme="minimal"] textarea { font-family: inherit; }
body[data-mywork-theme="minimal"][data-mywork-theme] .dcu-root, body[data-mywork-theme="minimal"][data-mywork-theme] .dcu-settings-page { --dcu-font: "Geist", "Noto Sans SC", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; }
body[data-mywork-theme="minimal"] [data-phase=hero] [class$="_headline"] { font-family: var(--mywork-serif); font-weight: 500; letter-spacing: -0.02em; }
body[data-mywork-theme="minimal"] .dcu-panel-head, body[data-mywork-theme="minimal"] .dcu-settings-heading h1, body[data-mywork-theme="minimal"] .mwtc-title, body[data-mywork-theme="minimal"] .dsh-st-card h3, body[data-mywork-theme="minimal"] h1, body[data-mywork-theme="minimal"] h2, body[data-mywork-theme="minimal"] .dcu-home-card span { font-family: var(--mywork-serif); font-weight: 500; letter-spacing: -0.01em; }
body[data-mywork-theme="minimal"] [data-composer-card] { border-radius: 8px !important; box-shadow: none !important; border: 1px solid var(--dsw-alias-border-l2) !important; }
body[data-mywork-theme="minimal"] .dcu-home-card, body[data-mywork-theme="minimal"] .mwtc-card, body[data-mywork-theme="minimal"] .mwi, body[data-mywork-theme="minimal"] .dsh-st-card { border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px; background: var(--dsw-alias-bg-layer-1); box-shadow: none; }
body[data-mywork-theme="minimal"] .dcu-home-card:hover, body[data-mywork-theme="minimal"] .dcu-home-card[aria-pressed=true] { box-shadow: 0 2px 8px rgba(0, 0, 0, 0.04); border-color: var(--dsw-alias-border-l3); }
body[data-mywork-theme="minimal"] .dcu-home-task, body[data-mywork-theme="minimal"] .mwtc-zbtn, body[data-mywork-theme="minimal"] .mwb-mini.framed, body[data-mywork-theme="minimal"] .mwr-in, body[data-mywork-theme="minimal"] .mwm-in, body[data-mywork-theme="minimal"] .mwb-in { border-radius: 6px; }
body[data-mywork-theme="minimal"] [data-composer-card] [class*="_primary"], body[data-mywork-theme="minimal"] .dsh-st-btn--primary, body[data-mywork-theme="minimal"] .mwm-primary, body[data-mywork-theme="minimal"] .mwi .btn { border-radius: 6px !important; box-shadow: none !important; color: var(--dsw-alias-label-primary-foreground) !important; }
body[data-mywork-theme="minimal"] .dcu-wb-session, body[data-mywork-theme="minimal"] .dcu-menu button, body[data-mywork-theme="minimal"] .dcu-settings-link { border-radius: 6px; }
body[data-mywork-theme="minimal"] .dcu-wb-section-label, body[data-mywork-theme="minimal"] .mwtc-title, body[data-mywork-theme="minimal"] .dcu-settings-group-label { letter-spacing: 0.05em; text-transform: uppercase; font-size: 12px; }
body[data-mywork-theme="minimal"] .mwr-pill, body[data-mywork-theme="minimal"] .dsh-st-chip { border-radius: 999px; font-size: 12px; letter-spacing: 0.04em; }
body[data-mywork-theme="minimal"] kbd { border: 1px solid var(--dsw-alias-border-l2); border-radius: 4px; background: var(--dsw-alias-bg-base); font-family: var(--mywork-mono); }
body[data-mywork-theme="minimal"] pre { border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px; }
body[data-mywork-theme="minimal"] button, body[data-mywork-theme="minimal"] [role="button"], body[data-mywork-theme="minimal"] a { transition: background-color 200ms cubic-bezier(0.16, 1, 0.3, 1), border-color 200ms cubic-bezier(0.16, 1, 0.3, 1), color 200ms cubic-bezier(0.16, 1, 0.3, 1), box-shadow 200ms cubic-bezier(0.16, 1, 0.3, 1); }
body[data-mywork-theme="minimal"] button:active { transform: scale(0.98); }
body[data-mywork-theme="minimal"] :focus-visible { outline: 2px solid var(--dsw-alias-label-primary); outline-offset: 2px; border-radius: 4px; }

/* 工业粗野 (brutalist-skill "Swiss Industrial Print" in light / "Tactical Telemetry" in dark): Archivo heavy headings, JetBrains Mono
   uppercase metadata, hazard red as the only accent, 90° corners everywhere, visible 1px compartment lines, scanlines in dark. */
body[data-mywork-theme="brutal"] {
  --mywork-mono: "JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  font-family: "Archivo", -apple-system, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif;
}
body[data-mywork-theme="brutal"] button, body[data-mywork-theme="brutal"] input, body[data-mywork-theme="brutal"] select, body[data-mywork-theme="brutal"] textarea { font-family: inherit; }
body[data-mywork-theme="brutal"][data-mywork-theme] .dcu-root, body[data-mywork-theme="brutal"][data-mywork-theme] .dcu-settings-page { --dcu-font: "Archivo", -apple-system, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif; }
body[data-mywork-theme="brutal"] #root *:not(svg):not(svg *):not([role="switch"]):not([role="switch"] *):not(input[type="checkbox"]):not(input[type="radio"]):not(img) { border-radius: 0 !important; }
body[data-mywork-theme="brutal"] [class*="_sidebarCol"] { border-right: 2px solid var(--dsw-alias-label-primary) !important; }
body[data-mywork-theme="brutal"] .dcu-head, body[data-mywork-theme="brutal"] .dcu-foot, body[data-mywork-theme="brutal"] .dcu-workspaces { border-color: var(--dsw-alias-label-primary) !important; }
body[data-mywork-theme="brutal"] .dcu-wb-section-label, body[data-mywork-theme="brutal"] .mwtc-title, body[data-mywork-theme="brutal"] .dcu-settings-group-label, body[data-mywork-theme="brutal"] .dcu-menu button, body[data-mywork-theme="brutal"] .dcu-im-tab, body[data-mywork-theme="brutal"] .dcu-settings-link, body[data-mywork-theme="brutal"] .mwk-tab, body[data-mywork-theme="brutal"] .dsh-st-chip, body[data-mywork-theme="brutal"] .mwr-pill, body[data-mywork-theme="brutal"] .mwb-foot { font-family: var(--mywork-mono); text-transform: uppercase; letter-spacing: 0.08em; font-size: 12px; }
body[data-mywork-theme="brutal"] { --mywork-display: "Archivo", -apple-system, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; }
body[data-mywork-theme="brutal"] [data-phase=hero] [class$="_headline"] { font-family: var(--mywork-display); font-weight: 900; letter-spacing: -0.04em; text-transform: uppercase; }
body[data-mywork-theme="brutal"] .dcu-panel-head, body[data-mywork-theme="brutal"] .dcu-home-card, body[data-mywork-theme="brutal"] .mwtc-card .mwtc-name, body[data-mywork-theme="brutal"] .dcu-wb-project-title, body[data-mywork-theme="brutal"] .dcu-settings-heading h1, body[data-mywork-theme="brutal"] .dsh-st-card h3, body[data-mywork-theme="brutal"] .ima-platform-name, body[data-mywork-theme="brutal"] h1, body[data-mywork-theme="brutal"] h2, body[data-mywork-theme="brutal"] h3 { font-family: var(--mywork-display); }
body[data-mywork-theme="brutal"] .dcu-panel-head, body[data-mywork-theme="brutal"] h1, body[data-mywork-theme="brutal"] h2, body[data-mywork-theme="brutal"] h3 { font-weight: 800; letter-spacing: -0.02em; text-transform: uppercase; }
body[data-mywork-theme="brutal"] [data-composer-card] { border: 2px solid var(--dsw-alias-label-primary) !important; box-shadow: 6px 6px 0 var(--dsw-alias-label-primary) !important; }
body[data-mywork-theme="brutal"] .dcu-home-card, body[data-mywork-theme="brutal"] .mwtc-card, body[data-mywork-theme="brutal"] .mwi, body[data-mywork-theme="brutal"] .dsh-st-card, body[data-mywork-theme="brutal"] .ima-platform { border: 1px solid var(--dsw-alias-label-primary); background: var(--dsw-alias-bg-layer-1); box-shadow: none; }
body[data-mywork-theme="brutal"] .dcu-home-card:hover, body[data-mywork-theme="brutal"] .dcu-home-card[aria-pressed=true], body[data-mywork-theme="brutal"] .mwtc-card.active { box-shadow: 4px 4px 0 var(--dsw-alias-brand-primary); border-color: var(--dsw-alias-label-primary); }
body[data-mywork-theme="brutal"] .dcu-home-card svg { color: var(--dsw-alias-brand-primary); }
body[data-mywork-theme="brutal"] [data-composer-card] [class*="_primary"], body[data-mywork-theme="brutal"] .dsh-st-btn--primary, body[data-mywork-theme="brutal"] .mwm-primary, body[data-mywork-theme="brutal"] .mwi .btn { box-shadow: 3px 3px 0 var(--dsw-alias-label-primary) !important; color: var(--dsw-alias-label-primary-foreground) !important; text-transform: uppercase; letter-spacing: 0.06em; }
body[data-mywork-theme="brutal"] .mwb-omni .mwb-in, body[data-mywork-theme="brutal"] .mwr-in, body[data-mywork-theme="brutal"] .mwm-in, body[data-mywork-theme="brutal"] .mwb-in { border: 1px solid var(--dsw-alias-label-primary); font-family: var(--mywork-mono); }
body[data-mywork-theme="brutal"] .mwb-bar { border-bottom: 1px solid var(--dsw-alias-label-primary); }
body[data-mywork-theme="brutal"] .dcu-wb-session.dcu-wb-selected, body[data-mywork-theme="brutal"] .dcu-menu button[aria-current], body[data-mywork-theme="brutal"] .dcu-settings-link[aria-current] { box-shadow: inset 3px 0 0 var(--dsw-alias-brand-primary); }
body[data-mywork-theme="brutal"] pre { border: 1px solid var(--dsw-alias-label-primary); }
body[data-mywork-theme="brutal"] button, body[data-mywork-theme="brutal"] [role="button"], body[data-mywork-theme="brutal"] a { transition: background-color 80ms linear, color 80ms linear, box-shadow 80ms linear; }
body[data-mywork-theme="brutal"] :focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 0; }
/* brutalist type runs one step smaller: dense telemetry, not display */
:root:has(body[data-mywork-theme="brutal"]) { --dsh-content-font-size: 13px; }
body[data-mywork-theme="brutal"] .dcu-root { font-size: 13px; }
body[data-mywork-theme="brutal"] .dcu-wb-project-title, body[data-mywork-theme="brutal"] .dcu-wb-session-title, body[data-mywork-theme="brutal"] .dcu-menu button, body[data-mywork-theme="brutal"] .dcu-footer-link, body[data-mywork-theme="brutal"] .dcu-settings-seat > button { font-size: 13px; }
body[data-mywork-theme="brutal"] .dcu-menu button, body[data-mywork-theme="brutal"] .dcu-im-tab { font-size: 11.5px; }
body[data-mywork-theme="brutal"] .dcu-panel-head { font-size: 16px; }
body[data-mywork-theme="brutal"] [data-phase=hero] [class$="_headline"] { font-size: 28px; line-height: 36px; }
body[data-mywork-theme="brutal"] .dcu-home-card { font-size: 12.5px; }
body[data-ds-dark-theme][data-mywork-theme="brutal"]::after { content: ""; position: fixed; inset: 0; pointer-events: none; z-index: 2147483000; background: repeating-linear-gradient(0deg, transparent 0 2px, rgba(0, 0, 0, 0.16) 2px 4px); }
@media (prefers-reduced-motion: reduce) { body[data-mywork-theme] * { transition-duration: 0.01ms !important; animation-duration: 0.01ms !important; } }
/* dsh derives every font shorthand (--dsw-font-xs-*, markdown, tables) from --dsw-font-family at :root, so a family must
   override the base variable on :root itself; body-level font-family alone leaves message text, the right-sidebar guide and
   hosted plugins on the system font. */
:root:has(body[data-mywork-theme="soft"]) { --dsw-font-family: "Plus Jakarta Sans", "Yuanti SC", "Noto Sans SC", "Microsoft YaHei UI", "Microsoft YaHei", "PingFang SC", sans-serif; --dsw-font-mono: "Geist Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace; --dsw-font-family-mono: "Geist Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace; }
:root:has(body[data-mywork-theme="minimal"]) { --dsw-font-family: "Geist", "Noto Sans SC", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; --dsw-font-mono: "Geist Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace; --dsw-font-family-mono: "Geist Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace; }
:root:has(body[data-mywork-theme="brutal"]) { --dsw-font-family: "Archivo", -apple-system, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif; --dsw-font-mono: "JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace; --dsw-font-family-mono: "JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace; }
/* Every family: the sidebar is its own tinted surface (warm sand / neutral grey / cool slate) with a hairline edge,
   solid on every platform (dsh blends it to 60 % on macOS, which washes the tint out). */
body[data-mywork-theme] [class*="_sidebarCol"] { background: var(--dsw-specific-sidebar-fill) !important; border-right: 1px solid var(--dsw-alias-border-l2); }
@media (prefers-reduced-motion: reduce) { body[data-mywork-theme="swiss"] * { transition-duration: 0.01ms !important; animation-duration: 0.01ms !important; } }
/* settings section */
.mwtc-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(168px, 1fr)); gap: 10px; margin-top: 8px; }
.mwtc-card { border: 0.5px solid var(--dsw-alias-border-l2); border-radius: 12px; padding: 10px; cursor: pointer; background: var(--dsw-alias-bg-layer-1); color: var(--dsw-alias-label-primary); text-align: left; transition: border-color .15s, box-shadow .15s; }
.mwtc-card:hover { border-color: var(--dsw-alias-border-l3); }
.mwtc-card.active { border-color: var(--dsw-alias-brand-primary); box-shadow: 0 0 0 2px color-mix(in srgb, var(--dsw-alias-brand-primary) 30%, transparent); }
.mwtc-swatch { display: flex; gap: 4px; margin-bottom: 8px; }
.mwtc-swatch span { flex: 1; height: 22px; border-radius: 6px; border: 0.5px solid rgba(127,127,127,.25); }
.mwtc-name { font-size: 13px; font-weight: 600; }
.mwtc-sub { font-size: 12px; color: var(--dsw-alias-label-secondary); margin-top: 2px; font-family: var(--mywork-mono, monospace); }
.mwtc-hint { font-size: 12px; color: var(--dsw-alias-label-secondary); margin: 6px 0 12px; line-height: 1.6; }
.mwtc-title { font-size: 13px; font-weight: 600; margin: 14px 0 4px; }
.mwtc-zoom { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; margin-top: 6px; }
.mwtc-zoom input[type=range] { flex: 1; min-width: 160px; height: 24px; accent-color: var(--dsw-alias-brand-primary); }
.mwtc-zoom .val { font-family: var(--mywork-mono, monospace); font-size: 12px; min-width: 44px; text-align: right; margin-right: 8px; font-variant-numeric: tabular-nums; }
.mwtc-zbtn { border: 0.5px solid var(--dsw-alias-border-l2); background: transparent; color: var(--dsw-alias-label-primary); border-radius: 8px; padding: 4px 10px; cursor: pointer; font: inherit; font-size: 12px; }
.mwtc-zbtn:hover { background: var(--dsw-alias-interactive-bg-hover); }
.mwtc-zbtn.on { border-color: var(--dsw-alias-brand-primary); color: var(--dsw-alias-brand-text, var(--dsw-alias-label-primary)); font-weight: 600; }
`

// ---------------------------------------------------------------------------
// Locale
// ---------------------------------------------------------------------------

const zh = {
  nav: '外观',
  intro: '一键切换 Claude Code / Codex / Swiss 开发者风格配色（Swiss 由 ui-ux-pro-max 设计系统生成：slate 灰阶 + 一个绿色强调色，IBM Plex Sans + JetBrains Mono）。风格保存在本浏览器并在刷新后恢复；明暗方案由 dsh 自身保存，两者独立组合。',
  mine: '风格',
  scheme: '明暗方案',
  current: '当前',
  zoom: '界面缩放',
  zoomHint: '整体放大 / 缩小侧栏、按钮和文字（本浏览器记忆）。会话正文的字号和行距请用 设置 → 常规 → 字号大小（12–17 px），缩放不改变行距比例。', zoomOut: '缩小', zoomIn: '放大',
  reset: '重置',
}
const en = {
  nav: 'Appearance',
  intro: 'Switch between Claude Code / Codex / Swiss developer palettes with one click (Swiss comes from the ui-ux-pro-max design system: slate scale + one green accent, IBM Plex Sans + JetBrains Mono). The style is kept in this browser and restored after reload; the light/dark scheme is stored by dsh itself, and the two combine freely.',
  mine: 'Style',
  scheme: 'Color scheme',
  current: 'current',
  zoom: 'UI zoom',
  zoomHint: 'Scale the whole UI (sidebar, buttons, text); remembered in this browser. For the conversation text size use Settings → General → Font size (12–17 px).', zoomOut: 'Zoom out', zoomIn: 'Zoom in',
  reset: 'Reset',
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readStored() {
  try { return window.localStorage.getItem(STORAGE_KEY) || null } catch { return null }
}
function writeStored(id) {
  try {
    if (id === null) window.localStorage.removeItem(STORAGE_KEY)
    else window.localStorage.setItem(STORAGE_KEY, id)
  } catch { /* private mode etc. */ }
}
const ZOOM_KEY = 'dsh-mywork-shell:zoom'
const ZOOM_MIN = 80; const ZOOM_MAX = 150
function readZoom() { try { const n = Number(window.localStorage.getItem(ZOOM_KEY)); return n >= ZOOM_MIN && n <= ZOOM_MAX ? n : 100 } catch { return 100 } }
function writeZoom(n) { try { if (n === 100) window.localStorage.removeItem(ZOOM_KEY); else window.localStorage.setItem(ZOOM_KEY, String(n)) } catch { /* ignore */ } }
function applyZoom(n) {
  const root = document.documentElement
  root.style.removeProperty('zoom') // older versions zoomed <html> directly
  if (n === 100) root.style.removeProperty('--mywork-zoom')
  else root.style.setProperty('--mywork-zoom', String(n / 100))
}
function familyById(id) {
  return FAMILIES.find((x) => x.id === id) || null
}
function injectStyles() {
  const el = document.createElement('style')
  el.setAttribute('data-plugin', PLUGIN)
  el.textContent = CSS
  document.head.appendChild(el)
  return () => { el.remove() }
}
function currentLang(ctx) {
  try {
    const snap = ctx.locale.getSnapshot()
    if (snap && typeof snap.active === 'string') return snap.active.toLowerCase().startsWith('zh') ? 'zh' : 'en'
  } catch { /* fall through */ }
  const nav = (typeof navigator !== 'undefined' && navigator.language) || 'en'
  return nav.toLowerCase().startsWith('zh') ? 'zh' : 'en'
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

exports.name = PLUGIN
exports.inject = ['theme', 'slots', 'locale']

exports.apply = function apply(ctx) {
  const theme = ctx.theme
  ctx.effect(() => injectStyles(), `${PLUGIN}: stylesheet`)
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), `${PLUGIN}: dictionaries`)
  const t = ctx.locale.bind(NS)

  // Active family = one override layer over the host theme (the official API
  // for third-party palettes). Unloading the plugin disposes the layer.
  let current = 'official'
  let disposeLayer = null
  const subs = new Set()
  const notify = () => { subs.forEach((fn) => { try { fn() } catch { /* ignore */ } }) }

  const applyFamily = (id) => {
    const fam = familyById(id) || FAMILIES[0]
    if (disposeLayer) { try { disposeLayer() } catch { /* ignore */ } disposeLayer = null }
    const tokens = overridesFor(fam)
    if (tokens) disposeLayer = theme.overrideTokens(PLUGIN, tokens)
    current = fam.id
    if (fam.id === 'official') document.body.removeAttribute('data-mywork-theme')
    else document.body.setAttribute('data-mywork-theme', fam.id)
    applyFonts(fam.fonts || null)
    notify()
  }
  /** Optional web fonts for a family (one <link>, swapped when the family changes; the UI falls back to system fonts while loading or offline). */
  const FONT_LINK_ID = 'mywork-shell-fonts'
  const applyFonts = (href) => {
    let link = document.getElementById(FONT_LINK_ID)
    if (!href) { if (link) link.remove(); return }
    if (!link) { link = document.createElement('link'); link.id = FONT_LINK_ID; link.rel = 'stylesheet'; document.head.appendChild(link) }
    if (link.getAttribute('href') !== href) link.setAttribute('href', href)
  }
  ctx.effect(() => () => {
    if (disposeLayer) { try { disposeLayer() } catch { /* ignore */ } disposeLayer = null }
    document.body.removeAttribute('data-mywork-theme')
    const link = document.getElementById(FONT_LINK_ID); if (link) link.remove()
  }, `${PLUGIN}: override layer`)

  const chooseFamily = (id) => { applyFamily(id); writeStored(id === 'official' ? null : id) }
  const chooseScheme = (id) => {
    try { theme.setTheme(id) } catch (e) { console.error(`[${PLUGIN}] setTheme failed`, e) }
  }

  // UI zoom (CSS zoom on #root + portal rules in CSS; works in Chromium, Safari and Firefox ≥ 126).
  let zoom = readZoom()
  applyZoom(zoom)
  ctx.effect(() => () => applyZoom(100), `${PLUGIN}: zoom`)
  const setZoom = (n) => { zoom = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, Math.round(n))); applyZoom(zoom); writeZoom(zoom); notify() }

  // Restore the remembered family right away (no event dependency).
  const stored = readStored()
  applyFamily(stored && familyById(stored) ? stored : DEFAULT_FAMILY)

  // Re-render the settings card whenever the host theme changes.
  ctx.effect(() => ctx.on('theme/change', notify, { global: true }), `${PLUGIN}: card refresh`)

  // ---- settings section ---------------------------------------------------
  function Card(props) {
    const h = React.createElement
    const { id, label, swatch, active, onPick, lang } = props
    return h('button', { type: 'button', className: 'mwtc-card' + (active ? ' active' : ''), onClick: () => onPick(id) },
      h('div', { className: 'mwtc-swatch' }, swatch.map((c, i) => h('span', { key: i, style: { background: c } }))),
      h('div', { className: 'mwtc-name' }, label[lang] || label.en),
      h('div', { className: 'mwtc-sub' }, id + (active ? ' · ' + t('current') : '')),
    )
  }

  function ThemeSection() {
    const h = React.createElement
    const [, force] = React.useState(0)
    React.useEffect(() => {
      const fn = () => force((n) => n + 1)
      subs.add(fn)
      return () => { subs.delete(fn) }
    }, [])
    const snap = theme.getTheme()
    const dark = snap.active.colorScheme === 'dark'
    const lang = currentLang(ctx)
    const famSwatch = (fam) => {
      const tk = dark ? fam.dark : fam.light
      if (!tk) return ['var(--dsw-alias-bg-base)', 'var(--dsw-alias-bg-layer-2)', 'var(--dsw-alias-brand-primary)', 'var(--dsw-alias-label-primary)']
      return [tk['--dsw-alias-bg-base'], tk['--dsw-alias-bg-layer-2'], tk['--dsw-alias-brand-primary'], tk['--dsw-alias-label-primary']]
    }
    const schemeSwatch = (id) => {
      const fam = familyById(current)
      const pick = (which) => (fam && fam[which]) ? [fam[which]['--dsw-alias-bg-base'], fam[which]['--dsw-alias-brand-primary']] : (which === 'dark' ? ['#151517', '#f9fafb'] : ['#ffffff', '#111111'])
      if (id === 'light') return pick('light')
      if (id === 'dark') return pick('dark')
      return [pick('light')[0], pick('dark')[0]]
    }
    return h('div', null,
      h('div', { className: 'mwtc-hint' }, t('intro')),
      h('div', { className: 'mwtc-title' }, t('mine')),
      h('div', { className: 'mwtc-grid' }, FAMILIES.map((fam) => h(Card, { key: fam.id, id: fam.id, label: fam.label, lang, swatch: famSwatch(fam), active: current === fam.id, onPick: chooseFamily }))),
      h('div', { className: 'mwtc-title' }, t('scheme')),
      h('div', { className: 'mwtc-grid' }, SCHEMES.map((s) => h(Card, { key: s.id, id: s.id, label: s.label, lang, swatch: schemeSwatch(s.id), active: snap.preference === s.id, onPick: chooseScheme }))),
      h('div', { className: 'mwtc-title' }, t('zoom')),
      h('div', { className: 'mwtc-hint' }, t('zoomHint')),
      h('div', { className: 'mwtc-zoom' },
        h('button', { className: 'mwtc-zbtn', 'aria-label': t('zoomOut'), title: t('zoomOut'), onClick: () => setZoom(zoom - 5) }, '−'),
        h('input', { type: 'range', 'aria-label': t('zoom'), min: ZOOM_MIN, max: ZOOM_MAX, step: 5, value: zoom, onChange: (e) => setZoom(Number(e.target.value)) }),
        h('button', { className: 'mwtc-zbtn', 'aria-label': t('zoomIn'), title: t('zoomIn'), onClick: () => setZoom(zoom + 5) }, '+'),
        h('output', { className: 'val', 'aria-live': 'polite' }, zoom + '%'),
        [90, 100, 110, 125].map((n) => h('button', { key: n, className: 'mwtc-zbtn' + (zoom === n ? ' on' : ''), onClick: () => setZoom(n) }, n === 100 ? t('reset') : n + '%')),
      ),
    )
  }

  // "外观" tab inside Settings → MyWork (slot declared by dsh-mywork-kit).
  ctx.slots.inject(TAB_SLOT, () => ctx.slots.register({
    name: TAB_SLOT, id: 'appearance', order: 20, label: () => t('nav'),
  }, function MyworkAppearanceTab() { return React.createElement(ThemeSection) }))
}

    return module.exports;
  }
});
